---
layout: page
title:  Architectural and Related Diagrams
type: resources
---
:page-liquid:

= Architectural and Related Diagrams

This page links to architectural and other related diagrams for
Calendaring and Scheduling.

Diagrams linked from this page are Copyright by The Calendaring and
Scheduling Consortium whether or not any copyright statement appears on
the diagram itself, and are made available under a Creative Commons
license; see
link:{{'/about/policies/copyright-licensing' | relative_url }}[Copyright and License Information].

* link:{{'/architectures/Calendaring%20Architecture.pdf' | relative_url }}[*Calendaring Service Architecture*]:
A high-level architectural diagram of the calendaring
and scheduling environment, from
link:{{'/about/technical-committees/tc-api' | relative_url }}[TC API].

* link:{{'/architectures/Task%20Architecture%201.0.pdf' | relative_url }}[*Task Architecture*]:
Overall architecture for Tasks (VTODOs) in a calendaring and scheduling
environment, from link:{{'/about/technical-committees/tc-tasks' | relative_url }}[TC TASKS].