---
layout: page
title:  Calendaring Systems Bug Reporting
type: resources
---
= Calendaring Systems Bug Reporting

_Page last updated 05 October 2015_

The following links and information have been contributed by vendor and open
source or academic developer members to provide a "one stop" source for bug
reporting for calendaring systems and applications developed by members of the
Consortium. We will periodically check with the contributing members to ensure
the information is as up to date as possible; however if you notice that an
entry does not work or appears to have been changed, please notify us at
mailto:info@calconnect.org[info@calconnect.org].

[cols="a,a,a",options="header"]
|===
|Vendor |Product |Reporting

|*1&1 Internet AG* |https://WEB.DE[WEB.DE] Kalender, http://GMX.com[GMX] Kalendar,
http://mail.com[mail.com] Organizer, http://GMX.com[GMX.com] Organizer
|1&1 does not yet have an external bug tracking system; please use this
mailto:carddavsupport@1und1.de[e-mail address] to report bugs related to
contacts and CardDAV.

|*BusyMac* |BusyCal and BusyContacts
|BusyMac does not have a formal public-facing site for reporting/tracking bugs
at this time. Please send any bug reports to the mailto:support@busymac.com[support e-mail address].

|*CMU* |http://cyrusimap.org[Cyrus] | https://git.cyrus.foundation/maniphest/[Report bugs]

|*FastMail* | http://www.fastmail.com[FastMail] |File support
ticket at http://www.fastmail.com/help/[Fastmail Help]; will be routed to
appropriate developer.

|*fruux* |http://sabre.io[sabre/dav]
|
Follow link:http://sabre.io/support/[Support] to the various trackers and support forums.

|*Milton* |https://github.com/miltonio/milton2[Milton] |File issues on https://github.com/miltonio/milton2/issues[GitHub]

|https://www.mozilla.org[*Mozilla*] |http://www.mozilla.org/projects/calendar/[Lightning]
|
https://bugzilla.mozilla.org/describecomponents.cgi?product=Calendar[Browse bugs for Lightning]

https://bugzilla.mozilla.org/enter_bug.cgi?product=Calendar[Report bugs for Lightning]

|*Open-Xchange* |https://open-xchange.com[Open-Xchange]
|https://bugs.open-xchange.com/enter_bug.cgi?product=OX%20App%20Suite&component=DAV[Enter bugs here.]

|*Oracle* |Oracle Communications Calendar Server
|https://community.oracle.com/community/fusion_middleware/webcenter/e-mail__calendar__%26_collaboration/oracle_communications_calendar_server[Enter bugs here.]

|*SchedJoules* |http://www.schedjoules.com[SchedJoules] | http://www.schedjoules.com/about/contact/[Contacts page], or send mailto:support@schedjoules.com[Comments and Remarks].

|*SmoothSync* | https://smoothsync.org[SmoothSync], CalDAV-Sync, CardDAV-Sync |
Contact mailto:support@dmfs.org[support@dmfs.org] or mailto:support@smoothsync.org[support@smoothsync.org]. CalConnect Members may also e-mail Marten directly.

|*Zimbra* | https://www.zimbra.com[Zimbra Calendar Server]
|
https://bugzilla.zimbra.com/enter_bug.cgi?product=ZCS&component=Calendar%20-%20Server[Report CalDAV or iMIP bugs]

https://bugzilla.zimbra.com/enter_bug.cgi?product=ZCS&component=Contacts%20-%20Server[Report CardDAV bugs]

|===
