---
layout: page
title: CalConnect Public Review and Comment List
type: resources
---

_Last Updated 15 August 2018_

This public discussion list was implemented to provide a public mechanism for review, comment and suggestions about draft CalConnect Standards and other documents which have been made available for public review and comment.

Completed CalConnect documents, including CalConnect Standards, are published and made generally available via the Document Register, except for a few internal documents mostly administrative in nature. However, in-progress documents and updates are usually restricted to representatives of CalConnect members.

During the development process, draft CalConnect Standards will be subject to public review and comment. In addition, a Technical Committee may, upon approval, make other draft documents available for public review and comment to seek as diverse an audience as possible. The Public Review and Comment mailing list is provided for those purposes. The audience is expected to be those interested in commenting and offering suggestions on a document; however the list is open to any and all participants that agree to and adhere to the rules of use.

For list information and to subscribe, please see http://lists.calconnect.org/listinfo.cgi/pubcomment-l-calconnect.org-l.

[IMPORTANT]
====
All CalConnect lists are moderated. You must subscribe to the list (and your subscription must be approved by the moderator) before you will be able to post to the list, receive messages posted on the list, or access the list archives.
====

=== Charter

The Calendaring and Scheduling Consortium Public Review and Comment Mailing List exists to allow public review and comment on selected documents being developed by CalConnect technical committees.

CalConnect's practice is to publish all completed and approved CalConnect documents on its website and make them generally available. However, in progress documents are generally restricted to representatives of CalConnect members until the document has been completed and is approved for publication. However, CalConnect has instituted a process for public review and comment where the developing technical committee and the TC coordinating committee feel that public review and comment are especially desirable or appropriate, and for appropriate public review and comment during the development process of CalConnect Standards.

This mailing list is provided as a mechanism to comment on CalConnect documents which have been posted as requesting review and comment. The list is open to any and all participants that agree to the rules of use. Generally the availability of a new document for public review and comment will be announced as broadly as appropriate, with links provided to this mailing list as the vehicle for making comments.

It is the responsibility of all participants on the list to ensure that their comments adhere to the CalConnect Intellectual Property Rights policy with respect to contributions. In particular, it is the policy of The Calendaring and Scheduling Consortium that no confidential material is to be discussed at or during Consortium activities (this list constitutes a Consortium activity). All information provided or discussed in Consortium activities is presumed to be public information and member participants are reminded that they should not discuss or reveal any confidential information of their respective companies.

While all participants on this list are free to contribute suggestions and comments, the actual process of development and revision of any CalConnect document must be made by the Technical Committees developing the document, and by members of the Consortium.

This list is moderated. Abuse of the list or the rules of use may result in an individual being cautioned or ultimately being removed from the list, at the sole discretion of the list moderators.

=== Rules of Use

Please use this resource in a professional and respectful manner. In particular, please refrain from "flames" and critiques of others' postings. Please keep your postings cogent and to the point.

* Do not attach files to your postings. Many list members block attachments which will result in a large amount of "blocked" traffic back to the list moderators. If you must have an attachment, put it on a web server and reference the URL.
* The list may not be used for product solicitations. Attempts to do so will result in the offender being removed from the list.
* If your subscribed e-mail address starts to bounce messages, it will be removed from the list after 2-3 days; the list moderators will attempt to contact the subscribed e-mail address if this happens.

By subscribing to this list and by posting to this list you accept and agree to abide by the above Charter and Rules of Use.
