---
layout: page
title: Registration Opens for CalConnect XVII, Feb 1-5, 2010
date: 2009-12-04
type: news
categories: announcements current-events general-information
excerpt: Registration is now open for CalConnect XVIII, February 1-5, 2010. CalConnect XVII will be hosted by the University of California at Irvine, Irvine, California. Logistics and registration information may be found at CalConnect XVII.
---

== Registration Opens for CalConnect XVII, Feb 1-5, 2010

Posted December 4, 2009

Registration is now open for CalConnect XVIII, February 1-5, 2010. CalConnect XVII will be hosted by the University of California at Irvine, Irvine, California. Logistics and registration information may be found at link:{{'/calconnect17' | relative_url}}[CalConnect XVII].

CalConnect XVII will consist of two Interoperability Test Events, a link:{{'/iop1002' | relative_url}}[regular test event] and a link:{{'/miop1002' | relative_url}}[Mobile Calendaring test event], on Monday, Tuesday, and Wednesday morning, followed by a CalConnect Roundtable (members  meeting) Wednesday afternoon through Friday afternoon.

Observers are welcome at the IOP test events and at the Roundtable; registration information and considerations may be found linked from the CalConnect XVII logistics page referenced above.

