---
layout: page
title: CalConnect publishes Proposal for Freebusy Read URL
date: 2009-04-15
type: news
categories: announcements general-information the-world-of-calendaring
excerpt: CalConnect’s FREEBUSY Technical Committee has just published a Proposal* for Freebusy Read URL. This Proposal defines a standardized form of Freebusy Read URL to improve interoperability between client and server implementations, while extending the functionality and utility through the use of optional parameters. Please see Freebusy Read URL.
---

== CalConnect publishes Proposal for Freebusy Read URL

[[node-342]]
Posted April 15, 2009 

CalConnect s FREEBUSY Technical Committee has just published a Proposal\* for Freebusy Read URL. This Proposal defines a standardized form of Freebusy Read URL to improve interoperability between client and server implementations, while extending the functionality and utility through the use of optional parameters. Please see link:/docs/CD0903%20Freebusy%20Read%20URL.pdf[Freebusy Read URL].

*CalConnect Proposals are experimental specifications intended for research and exploration, e.g. through trial implementations, to determine usefulness and applicability. Proposals deemed successful are candidates to be offered to an appropriate standards body for adoption and progression as a standard.&nbsp;



Categories:&nbsp;

link:/news/announcements[Announcements]

link:/news/general-information[General Information]

link:/news/the-world-of-calendaring[The World of Calendaring]

