---
layout: page
title: LINK Property Proposal and Timezone Service and XML Specification Proposals Published
date: 2010-07-09
type: news
categories: announcements general-information special-focus the-world-of-calendaring
excerpt: The EVENTPUB Technical Committee has published LINK Property Extension to iCalendar, and the proposal has been submitted to the IETF as an Internet Draft. Please see LINK Property Extension to iCalendar. This proposal introduces a new iCalendar property LINK to provide ancillary information for iCalendar components.
---

== LINK Property Proposal and Timezone Service and XML Specification Proposals Published

[[node-293]]
Posted July 9, 2010 

The EVENTPUB Technical Committee has published __LINK Property Extension to iCalendar__, and the proposal has been submitted to the IETF as an Internet Draft. Please see link://CD1006%20LINK%20Property.shtml[LINK Property Extension to iCalendar]. This proposal introduces a new iCalendar property LINK to provide ancillary information for iCalendar components.

The TIMEZONE Technical Committee has published _Timezone Service Protocol_ and __Timezone XML Specification__, and the proposals have been submitted to the IETF as Internet Drafts. Please see link://CD1007%20Timezone%20Service.shtml[Timezone Service Protocol] and link://CD1008%20Timezone%20XML.shtml[Timezone XML Specification]. The Timezone Service Protocol defines a timezone service protocol that allows reliable, secure and fast delivery of timezone information to client systems such as calendaring and scheduling applications or operating systems. The Timezone XML Specification describes a format for describing timezone information for software and services.

CalConnect Proposals are experimental specifications which may be submitted to the IETF or other standards bodies for progression to become standards.&nbsp;

https://www.addthis.com/bookmark.php?v=300https://www.addthis.com/bookmark.php?v=300https://www.addthis.com/bookmark.php?v=300https://www.addthis.com/bookmark.php?v=300https://www.addthis.com/bookmark.php?v=300

Categories:&nbsp;

link:/news/announcements[Announcements]

link:/news/general-information[General Information]

link:/news/special-focus[Special Focus]

link:/news/the-world-of-calendaring[The World of Calendaring]

