---
layout: page
title: CalWS-Rest Restful Web Services Protocol for Calendaring published
date: 2010-09-13
type: news
categories: announcements current-events general-information special-focus the-world-of-calendaring
excerpt: The XML Technical Committee has published CalWS-Rest Restful Web Services Protocol for Calendaring. This work was undertaken in conjunction with the OASIS WS CALENDAR Technical Committee and will become a component of the WS-Calendar specification, in addition to being progressed within CalConnect as a calendaring operations API for web services. Please see CalWS-Rest Restful Web Services Protocol for Calendaring.
---

== CalWS-Rest Restful Web Services Protocol for Calendaring published

[[node-286]]
Posted September 13, 2010 

The XML Technical Committee has published CalWS-Rest Restful Web Services Protocol for Calendaring. This work was undertaken in conjunction with the OASIS WS CALENDAR Technical Committee and will become a component of the WS-Calendar specification, in addition to being progressed within CalConnect as a calendaring operations API for web services. Please see link:/docs/CD1011%20CalWS-Rest%20Restful%20Web%20Services%20Protocol%20for%20Calendaring%20V1.0.pdf[CalWS-Rest Restful Web Services Protocol for Calendaring].



Categories:&nbsp;

link:/news/announcements[Announcements]

link:/news/current-events[Current Events]

link:/news/general-information[General Information]

link:/news/special-focus[Special Focus]

link:/news/the-world-of-calendaring[The World of Calendaring]

