---
layout: page
title: May 2010 CalConnect Interoperability Test Event Report Published
date: 2010-07-22
type: news
categories: announcements current-events general-information
excerpt: The public report from the CalConnect Interoperability Test Event on May 24-26 2010 has been published. This test event included both a “regular” test event and a Mobile Calendaring test event focused on ActiveSync. The test event was hosted by Carnegie Mellon University in conjunction with Roundtable XVIII. Please see May 2010 CalConnect Interoperability Test Event Report.
---

== May 2010 CalConnect Interoperability Test Event Report Published

[[node-292]]
Posted July 22, 2010 

The public report from the CalConnect Interoperability Test Event on May 24-26 2010 has been published. This test event included both a regular test event and a Mobile Calendaring test event focused on ActiveSync. The test event was hosted by Carnegie Mellon University in conjunction with Roundtable XVIII. Please see link:/docs/CD1009%20May%202010%20CalConnect%20Interoperability%20Test%20Event%20Report.pdf[May 2010 CalConnect Interoperability Test Event Report].

The complete internal test event report is available to CalConnect members on the CalConnect website members area.

https://www.addthis.com/bookmark.php?v=300https://www.addthis.com/bookmark.php?v=300https://www.addthis.com/bookmark.php?v=300https://www.addthis.com/bookmark.php?v=300https://www.addthis.com/bookmark.php?v=300

Categories:&nbsp;

link:/news/announcements[Announcements]

link:/news/current-events[Current Events]

link:/news/general-information[General Information]

