---
layout: page
title: Registration is open for CalConnect XXI May 23-27 at NASA Ames Research Center
date: 2011-04-05
type: news
categories: announcements current-events general-information
excerpt: Registration is now open for CalConnect XXI, May 23-27, 2011, at NASA Ames Research Center, Moffett Field, Mountain View, California. Please see link://calconnect21.shtml for logistics and registration information.
---

== Registration is open for CalConnect XXI May 23-27 at NASA Ames Research Center

[[node-263]]
Posted April 5, 2011 

Registration is now open for CalConnect XXI, May 23-27, 2011, at NASA Ames Research Center, Moffett Field, Mountain View, California. Please see link://calconnect21.shtml for logistics and registration information.

As usual, we will be conducting an Interoperability Test Event Monday-Wednesday, May 23-25. Information about the Test Event is at link://iop1105.shtml[]. The Roundtable Members  Meeting will be Wednesday-Friday May 25-27.

We will be conducting a Workshop on Tasks on Wednesday afternoon during the Roundtable from 1:30 to 3:30. This workshop is open to non-CalConnect members, and you do not have to register for the Roundtable to attend; however you do need to register for the workshop. See the logistics page noted above for more information. NASA will also offer a tour of the Ames Rsearch Center on Friday afternoon following the close of our meeting.

The meeting venue is at the NASA Ames Conference Center, 500 Severyns Avenue, located in the NASA Ames Research Center on Moffett Field. The logistics page includes a map of the area (including the location of the meeting venue and hotel).

Note well: NASA Ames is a government installation and has security controls. If you are a U.S. citizen you must show your driver s license or proof of identify If you are a non-citizen permanent resident you will need to show a driver s license or passport and your green card). If you are a non-citizen visitor, you will need a special invitation from NASA and visitor pass; see the logistics page for more details.

The Conference Hotel will be the Sheraton Sunnyvale, which is very close to NASA Ames. They are offering a discounted rate for our conference. This is a courtesy rate and we do not have a room block, so you should book early to ensure you get the special rate. We have a special booking arrangement so be sure to review the Hotel section of the logistics page carefully.

We will be announcing additional and special sessions of interest as more material becomes available. We expect to set the actual schedule for TC sessions by mid-month and announce the topical agendas early in May.



Categories:&nbsp;

link:/news/announcements[Announcements]

link:/news/current-events[Current Events]

link:/news/general-information[General Information]

