---
layout: page
title: CalConnect announces special registration fees for CalConnect XXII in Prague
date: 2011-06-17
type: news
categories: announcements current-events special-focus
excerpt: CalConnect has announced special reduced registration fees for some participants in the upcoming CalConnect XXII event, hosted by Kerio Technologies in Prague, Czech Republic on October 3-7, 2011. The special rates are
---
:page-liquid:

== CalConnect announces special registration fees for CalConnect XXII in Prague

CalConnect has announced special reduced registration fees for some participants in the upcoming CalConnect XXII event, hosted by Kerio Technologies in Prague, Czech Republic on October 3-7, 2011. The special rates are:

* Non-members may register one person for the Interoperability Test Event, the Roundtable members meeting (as an observer), or both, for a single fee of $350.
* Members who are not calendaring vendors may register one person for the Interoperability Test Event for $350.

For more information please see link:{{'/calconnect22' | relative_url}}[CalConnect XXII] or contact CalConnect via or website by e-mail at mailto:contact@calconnect.org' | relative_url}}[contact@calconnect.org].


