---
layout: page
title: Interoperability Testing Underway at CalConnect XXII
date: 2011-10-04
type: news
categories: announcements special-focus the-world-of-calendaring
excerpt: Today is the second day of the interoperability testing event at CalConnect XXII in Prague, hosted by Kerio Technologies. Fifteen people present from eight organizations and individual members, plus one testing remotely.
---
:page-liquid:

== Interoperability Testing Underway at CalConnect XXII

Posted October 4, 2011 

Today is the second day of the interoperability testing event at CalConnect XXII in Prague, hosted by Kerio Technologies. Fifteen people present from eight organizations and individual members, plus one testing remotely.

* Andrew McMillan  DAViCal server and aCal Android client
* Apple  Apple clients and servers
* Intel  SyncEvolution open source client
* Kerio Technologies  Kerio Connect
* Oracle  Oracle Communications Calendar Server
* RPI  Bedework open source CalDAV server
* Stylite AG  EGroupware
* Synchronica  Synchronica Mobile Gateway

The test event will continue until noon Wednesday; the Roundtable Technical Conference begins at 13:00 on Wednesday.


