---
layout: page
title: Friday afternoon; wrapping up CalConnect XXII in Prague
date: 2011-10-07
type: news
categories: announcements current-events general-information
excerpt: The meeting is drawing to a close with the last Technical Committee session, followed by the wrapup and our Plenary meeting. It’s been a great five days, although quite tiring as always. We are very happy with the European involvement, including the presence of representatives from four non-members, which has injected new perspectives and concerns into the technical discussions to the benefit of everyone.
---

== Friday afternoon: wrapping up CalConnect XXII in Prague

Posted October 7, 2011 

The meeting is drawing to a close with the last Technical Committee session, followed by the wrapup and our Plenary meeting. It s been a great five days, although quite tiring as always. We are very happy with the European involvement, including the presence of representatives from four non-members, which has injected new perspectives and concerns into the technical discussions to the benefit of everyone.

Additionally the CalConnect Internationally discussion, about what CalConnect should do to better support and allow more involvement from people based in Europe, produced a number of ideas in a variety of areas, and we have suggestions for our Technical Committee operating processes, our Steering Committee and our Board on possibilities going forward.

We are also delighted to announce that Apple will host CalConnect XXIII, which will be held the week of January 30  February 3 in Cupertino, California.&nbsp;


