---
layout: page
title: CalConnect Adopts Creative Commons and Apache Licenses
date: 2011-05-20
type: news
categories: announcements general-information special-focus the-world-of-calendaring
excerpt: CalConnect will now publish new and updated documents and other material under a Creative Commons license or, for code artifacts such as schemas, the Apache 2 License, replacing its prior terms of document availability. The intent is to make it as easy as possible for CalConnect material to be used, by publishing under standard and universal license terms. Please see Copyright and Licensing for Published Material for more information.
---

== CalConnect Adopts Creative Commons and Apache Licenses

[[node-258]]
Posted May 20, 2011 

CalConnect will now publish new and updated documents and other material under a Creative Commons license or, for code artifacts such as schemas, the Apache 2 License, replacing its prior terms of document availability. The intent is to make it as easy as possible for CalConnect material to be used, by publishing under standard and universal license terms. Please see link://copyrightlicense.shtml[Copyright and Licensing for Published Material] for more information.

https://www.addthis.com/bookmark.php?v=300https://www.addthis.com/bookmark.php?v=300https://www.addthis.com/bookmark.php?v=300https://www.addthis.com/bookmark.php?v=300https://www.addthis.com/bookmark.php?v=300

Categories:&nbsp;

link:/news/announcements[Announcements]

link:/news/general-information[General Information]

link:/news/special-focus[Special Focus]

link:/news/the-world-of-calendaring[The World of Calendaring]

