---
layout: page
title: CalConnect Roundtable as of Thursday afternoon 6 October
date: 2011-10-06
type: news
categories: current-events the-world-of-calendaring
excerpt: The Roundtable technical conference is going well. We have 20 participants which for our very first full CalConnect event in Europe is pretty respectable, and this includes four non-member organizations (ARC Informatique, DHL, Intel open source lab, and Stylite AG.
---
:page-liquid:

== CalConnect Roundtable as of Thursday afternoon 6 October

Posted October 6, 2011 

The Roundtable technical conference is going well. We have 20 participants which for our very first full CalConnect event in Europe is pretty respectable, and this includes four non-member organizations (ARC Informatique, DHL, Intel open source lab, and Stylite AG.

We moved the regular Technical Committee sessions to the afternoon to allow people in North America to join the sessions via GotoMeeting, which gave us time for symposia and workshops Thursday and Friday morning. This morning the symposia were "`The Evolution of Internet Calendaring Standards`" and "`Integrating Internet Calendaring Systems into products and services`".

Friday morning we is a workshop on Tasks (VTODOs) and how iCalendar should be extended to support new requirements such as project management, energy scheduling, and so forth. And we will have a BOF on "`CalConnect Internationally`", to discuss how CalConnect can make itself more accessible and available to international members (in particular Europe, at the moment). I ve heard some good ideas so far and look forward to the group discussion, as it will certainly inform CalConnect's decisions about going forward internationally.

Dave Thewlis +
CalConnect Executive Director


