---
layout: page
title: Registration is open for CalConnect XXIV May 21-25, 20012, Chattanooga, Tennessee
date: 2012-03-16
type: news
categories: announcements current-events general-information
excerpt: Registration is now open for CalConnect XXIV, May 21-25, 2012, in Chattanooga, Tennessee, hosted by Patricia Egen Consulting.  Please see CalConnect XXIV for logistics and registration information.  As usual, the first 2.5 days will be the Interoperability Test Event; the remainder of the week (Wednesday lunch through Friday mid-afternoon) will be the Roundtable Technical Conference.  Early booking at the conference hotel is recommended as the block rate expires on 3 May or when the block is exhausted, whichever happens first.
---

== Registration is open for CalConnect XXIV May 21-25, 20012, Chattanooga, Tennessee

[[node-235]]
Posted March 16, 2012 

Registration is now open for link://calconnect24.shtml[CalConnect XXIV], May 21-25, 2012, in Chattanooga, Tennessee, hosted by Patricia Egen Consulting.&nbsp; Please see link://calconnect24.shtml[CalConnect XXIV] for logistics and registration information.&nbsp; As usual, the first 2.5 days will be the Interoperability Test Event; the remainder of the week (Wednesday lunch through Friday mid-afternoon) will be the Roundtable Technical Conference.&nbsp; Early booking at the conference hotel is recommended as the block rate expires on 3 May or when the block is exhausted, whichever happens first.

&nbsp;

https://www.addthis.com/bookmark.php?v=300https://www.addthis.com/bookmark.php?v=300https://www.addthis.com/bookmark.php?v=300https://www.addthis.com/bookmark.php?v=300https://www.addthis.com/bookmark.php?v=300

Categories:&nbsp;

link:/news/announcements[Announcements]

link:/news/current-events[Current Events]

link:/news/general-information[General Information]

