---
layout: page
title: CalConnect Leadership Changes to Board of Directors and Steering Committee
date: 2012-08-09
type: news
categories: announcements current-events general-information special-focus
excerpt: CalConnect announces new members on its Board of Directors, and on its Steering Committee (charged with the technical direction of the consortium).
---

== CalConnect Leadership Changes to Board of Directors and Steering Committee

[[node-229]]
Posted August 9, 2012 

CalConnect announces new members on its Board of Directors, and on its Steering Committee (charged with the technical direction of the consortium).

On the Board of Directors, Ciny Joy (Oracle) and Scott Mace (HealthLeaders Media) join Gary Schwartz (Rensselaer Polytechnic Institute), Pam Taylor (Sterling Commerce) and Dave Thewlis (DCTA Inc.). Mr. Mace is also known as the author of http://calendarswamp.blogspot.com[The Calendar Swamp] blog.

On the Steering Committee, Andrew McMillan (individual member), Carnegie Mellon University, Intand, and Kerio Technologies join Apple, Oracle, Rensselaer Polytechnic Institute and the University of California.

CalConnect thanks the members and individuals who are donating their time and effort to leading and improving CalConnect and enabling it to fulfill its mission of calendaring and scheduling interoperability. We also thank those members and individuals who are stepping down from the Board (Kellie Hunter, People Cube, and Pat Egen, Patricia Egen Consulting) and the Steering Committee (NASA, Patricia Egen Consulting, PeopleCube, and the University of Wisconsin) for the time and effort they have devoted to CalConnect. &nbsp;

https://www.addthis.com/bookmark.php?v=300https://www.addthis.com/bookmark.php?v=300https://www.addthis.com/bookmark.php?v=300https://www.addthis.com/bookmark.php?v=300https://www.addthis.com/bookmark.php?v=300

Categories:&nbsp;

link:/news/announcements[Announcements]

link:/news/current-events[Current Events]

link:/news/general-information[General Information]

link:/news/special-focus[Special Focus]

