---
layout: page
title: CalConnect is returning to Europe; October 1-5, 2012, Zürich, Switzerland, hosted by Google
date: 2012-08-24
type: news
categories: announcements current-events general-information
excerpt: Our first European conference was last October, hosted by Kerio Technologies in Prague. It was very successful and the European attendees encouraged us to return the following year. Therefore, CalConnect XXV will take place in Zürich, Switzerland on October 1-5, 2012 -- less than six weeks from now, hosted by Google.
---
:page-liquid:

== CalConnect is returning to Europe: October 1-5, 2012, Zürich, Switzerland, hosted by Google

Our first European conference was last October, hosted by Kerio Technologies in Prague. It was very successful and the European attendees encouraged us to return the following year. Therefore, link:{{'/calconnect25' | relative_url}}[CalConnect XXV] will take place in Zürich, Switzerland on October 1-5, 2012  less than six weeks from now, hosted by http://www.google.com' | relative_url}}[Google].

We encourage our European colleagues and others interested in Calendaring and Scheduling to join us. We re working to make this event as attractive as possible to organizations that are not currently members but have thought about exploring CalConnect, and a European event is a chance for people to participate in a CalConnect member meeting without having to incur the travel costs and time of coming to North America.

CalConnect is a collaboration between calendaring and scheduling vendors and users. It was established to further interoperability between calendaring and scheduling implementations, and works towards this purpose by driving the evolution of calendaring and scheduling standards through technical committee work, holding regular interoperability testing events, and hosting regular conferences, workshops and symposia focused on calendaring and scheduling.

European companies were among CalConnect's earliest members members, and as standards and interoperability are both central to CalConnect's mission and are strong core values of European Information Technology, we have long recognized the importance of increasing European involvement in CalConnect. To that end we held special events in Europe and 2007 and 2008 in preparation for having a regular CalConnect conference in Europe in 2011. This autumn's event in Zürich is one which we hope will continue with even greater European participation in CalConnect's interoperable calendaring and scheduling projects.

*Overview*

Our venue will be Google's Zürich campus at Brandschenkestrasse 110, 8002 Zürich. All events of the CalConnect week, October 1-5, except for the Monday IOP test event dinner and the Thursday Roundtable dinner will take place on Google's campus. Full information about the conference may be found at link:{{'/calconnect25' | relative_url}}[CalConnect XXV] including the week's schedules, registration, and logistics information including accommodation.

Monday, Tuesday, and Wednesday morning, October 1-3, will be our Interoperability Test Event, ending with lunch on Wednesday. Wednesday afternoon (beginning with lunch), Thursday, and Friday, October 3-5, will be the Technical Conference (Roundtable) which will include workshops, symposia, and technical committee sessions: briefings on what the CalConnect technical committees are doing, and discussions of problems, alternatives, and participation in the work of the Technical Committees.

We are delighted to announce that Google, our host, will be actively participating in the Interoperability Test Event as well as the Technical Conference.

*Registration and Fees*

You must register separately for the Interoperability Test Event and the Roundtable Technical Conference. Please see link:{{'/regtypes' | relative_url}}[Registration and Fees] for more information and registration forms.

Special Fees for This Event: $350 U.S. per person for non-members to cover either the Interoperability Test Event, the Technical Conference, or both. (Non-members may always participate in the Interoperability Test Events, although the registration fee is usually greater for non-members), and may attend a single Roundtable as observers to determine if they are interested in joining CalConnect. CalConnect is also offering a special Interoperability Test Event fee of $350 for one person for non-vendor members of CalConnect.

We encourage you to register as soon as possible. Upon registration you will be invoiced for the amount due. However, you may choose to pay later, including at the event, if it is more convenient.

*Who and What is CalConnect?*

We are a collaboration between calendaring and scheduling vendors and users, established to further interoperability between calendaring and scheduling implementations, and work towards this purpose by driving the evolution of calendaring and scheduling standards through technical committee work, holding regular interoperability testing events, and hosting regular conferences, workshops and symposia focused on calendaring and scheduling. See our current member list at link:{{'/mbrlist' | relative_url}}[CalConnect Members]. Learn more about CalConnect at our link:{{'/' | relative_url}}[website] and our link:{{'/blog' | relative_url}}, and from our newsletter link:{{'/minutes' | relative_url}}[CalConnect Minutes], published after each CalConnect Technical Conference (Roundtable). You can find out more about membership in CalConnect at link:{{'/membership' | relative_url}}[CalConnect Membership].

*What is CalConnect currently focused on?*

You may find brief descriptions of the current work items of our Technical Committees at link:{{'/currentwork' | relative_url}}[Current Work].

*Questions and Feedback:*

Please contact us at mailto:contact@calconnect.org[contact@calconnect.org] with questions or feedback.

In particular, if you are interested in the Interoperability Test event and would like to suggest specific areas of testing, or potential participants, we want to know. If you have specific areas of interest or topics which you would like to see addressed in the workshops and symposia, please let us know about that as well! Also, feel free to send this e-mail on to others who you feel might be interested, or contact us and ask us to invite them as well.

You are also welcome to contact me directly with questions and suggestions.

Please join us in Zürich!


*More Information:*

More information about the test event, the technical conference, and the workshops may be found below. The schedule for the week may be viewed at link:{{'/calconnect25#schedule' | relative_url}}[CalConnect XXV Schedule]. The entire set of logistics information, including travel, hotel booking, schedule, and as we get closer to the event, topical agendas and final topics for the workshops and symposia, may be viewed at link:{{'/calconnect25' | relative_url}}[CalConnect XXV].

*Interoperability Testing*

The Interoperability Testing will take place Monday and Tuesday, October 1-2, plus Wednesday morning the 3rd. Our interoperability test events offer those with calendaring implementations a chance to test against others one-on-one; the event is structured to allow "`testing pairs`" where you will get a chance to test with everyone in the course of event.

The exact testing scenarios will be decided based on who is coming and what (and with whom) they want to test. As of today we will definitely plan to test the following areas:

iSchedule +
iCalendar/iMIP/iTIP and iMIP gateways +
CalDAV access +
CalDAV calendar sharing and notifications +
CalDAV scheduling, including implicit scheduling +
CardDAV +
The new Timezone Service Protocol +
CalWS, the Web Services protocol for calendaring** +
If there is interest, synchronization testing for mobile clients in general

Please see link:{{'/iop1210' | relative_url}}[CalConnect XXV IOP Test Event] for more information.

**CalWS is being developed in part to support of the WS Calendar specification from OASIS as part of the NIST Smart Grid initiative; however it is a general implementation of calendaring and scheduling operations via web services. CalWS testing is dependent upon at least two implementations participating.

*Technical Workshops and Symposia*

Thursday and Friday mornings will be dedicated to four 90 minute symposia and workshops, which are included in the Roundtable Registration. We have not finalized the subjects as yet but the areas under discussion include:

Improving the web calendaring experience for end users +
Best practices for publishing iCalendar data to ensure optimum interoperability +
Internationalization/Localization for Calendaring data +
Calendaring Futures and CalConnect directions

The link:{{'/calconnect25#schedule' | relative_url}}[CalConnect XXV Schedule] will be updated with the topics and speakers for the workshops and symposia as they are identified.

*Roundtable (Technical Conference)*

At each CalConnect event, the Roundtable offers an opportunity for each of the CalConnect Technical Committees to present its work, invite suggestions, and conduct open discussions with the attendees on issues or topics under deliberation in the technical committee. In order to facilitate people in North America joining the Roundtable portion of the week's events, the Roundtable sessions will be held Wednesday, Thursday and Friday afternoons, as will be shown in the CalConnect XXV Schedule. The schedule includes

Opening and introduction to CalConnect +
Report from the Interoperability Test Event +
Technical Committee sessions for all CalConnect TCs +
Opportunities for BOFs ("`birds of a feather`" discussions) +
Final wrapup and summary of all Technical Committee sessions +
CalConnect Plenary Session

The conference will conclude no later than 18:00 on Friday, October 5th.

*Social Events:*

There will be a dinner for all Interoperability Test Event participants on Monday Evening, a Reception on Wednesday evening (at Google) for all participants in either the Test Event and/or the Technical Conference, and a dinner for all Technical Conference participants on Thursday evening.

*Meals*

Your registration to the Interoperability Test Event or the Roundtable Technical Conference includes lunch and morning and afternoon refreshments for the period of the event, plus the reception Wednesday evening. In addition, registration to the test event includes the Monday evening IOP test event dinner, and registration to the technical conference includes the Thursday evening Roundtable dinner. Please note that breakfast is not included as it is generally included with your hotel package.


