---
layout: page
title: Registration is now open for CalConnect XXVI, January 28-February 1, 2013
date: 2012-11-16
type: news
categories: announcements current-events general-information
excerpt: Registration is now open for CalConnect XXVI, January 28 – February 1, 2013, hosted by Oracle in Santa Clara, California. Monday and Tuesday all day and Wednesday morning will be the Interoperability Test Event; Wednesday afternoon, Thursday, and Friday will be the CalConnect Roundtable Technical Conference.
---

== Registration is now open for CalConnect XXVI, January 28-February 1, 2013

Posted November 16, 2012 

Registration is now open for link:{{'/calconnect26' | relative_url}}[CalConnect XXVI], January 28  February 1, 2013, hosted by Oracle in Santa Clara, California. Monday and Tuesday all day and Wednesday morning will be the Interoperability Test Event; Wednesday afternoon, Thursday, and Friday will be the CalConnect Roundtable Technical Conference.

Logistics information for this event may be found at link:/calconnect26 including travel, preliminary hotel, registration, and other planning information. A general schedule is posted, but will be updated nearer to the event with the actual session schedule and with topical agendas for the schedule.

The meeting venue is on the Oracle campus at 4040 Palm Drive, Santa Clara, California. Hotel information is preliminary as we have not selected a conference hotel yet; there are a number of hotels in the area and a list provided by Oracle is available on the logistics page linked above. The exact schedule for TC Sessions is not yet fixed but should be determined by the beginning of January.

Early registration for the Roundtable will be $350 through 11 January, 2013, and $395 after that date. See link:{{'/regtypes' | relative_url}}[Registration Information] for registration forms. Please note that the early registration about applies so long as you register <= 11 January, even if you don't actually pay until the event. Your organization need not be a member to attend a single CalConnect Roundtable Technical Conference as an observer to determine your interest in joining.

More information about the Interoperability Test Event will be posted separately.

