---
layout: page
title: Interoperability Testing at CalConnect XXVIII
date: 2013-09-27
type: news
categories: current-events special-focus the-world-of-calendaring
excerpt: The Interoperability Test Event at CalConnect XXVIII featured 5 clients and 8 CalDAV servers tested by 13 on-site participants and two remote. In addition to the “regular” CalDAV and iMIP client/server and server/server testing, significant achievements include
---

== Interoperability Testing at CalConnect XXVIII

[[node-191]]
Posted September 27, 2013 

The Interoperability Test Event at CalConnect XXVIII featured 5 clients and 8 CalDAV servers tested by 13 on-site participants and two remote. In addition to the regular CalDAV and iMIP client/server and server/server testing, significant achievements include

* First (and successful) tests of jCal, the JSON format for iCalendar, tested for at least three servers
* CalDAV Managed Attachments, tested by multiple clients and servers
* Timezones By Reference (including servers/clients behavior if timezone data not sent, and CalDAV extensions to advertise Timezones by Reference (e.g. Timezone Service Protocol enabled)
* Initial testing of Prefer Header, a new specification allowing a WebDAV client to request certain behaviors be implemented by a server while constructing a response to a successful request
* VPOLL support on servers and interaction with existing clients
* Testing new VTODO properties/values defined by CalConnect TC-TASKS to verify they are supported by servers and clients
* In-depth review of the CalDAV Tester Suite and how to implement and use it

We invite everyone interested in interoperability testing to join the test event at Mozilla in San Francisco at CalConnect XXIX, February 3-7, 2014.

https://www.addthis.com/bookmark.php?v=300https://www.addthis.com/bookmark.php?v=300https://www.addthis.com/bookmark.php?v=300https://www.addthis.com/bookmark.php?v=300https://www.addthis.com/bookmark.php?v=300

Categories:&nbsp;

link:/news/current-events[Current Events]

link:/news/special-focus[Special Focus]

link:/news/the-world-of-calendaring[The World of Calendaring]

