---
layout: page
title: Interoperable Calendaring means never, never, ever having to enter an appointment on more than one machine
date: 2013-01-14
type: news
categories: general-information special-focus the-world-of-calendaring
excerpt: In the context of CalConnect’s mission, to advance interoperable calendaring & scheduling in practical and useful ways, one of our major activities is to promote open-standards based calendaring and scheduling to the general public as well as the information technology industry. From time to time, we receive unsolicited help in bringing our message to the general public, such as David Pogue’s column in last week’s New York Times, “Bringing the Calendar Up to Date” (http://www.nytimes.com/2013/01/08/technology/personaltech/mixing-and-matching-to-create-the-near-perfect-digital-calendar-state-of-the-art.html?pagewanted=all).
---

== Interoperable Calendaring means never, never, ever having to enter an appointment on more than one machine

Posted January 14, 2013 

In the context of CalConnect s mission, to advance interoperable calendaring & scheduling in practical and useful ways, one of our major activities is to promote open-standards based calendaring and scheduling to the general public as well as the information technology industry. From time to time, we receive unsolicited help in bringing our message to the general public, such as David Pogue s column in last week s New York Times, Bringing the Calendar Up to Date (http://www.nytimes.com/2013/01/08/technology/personaltech/mixing-and-matching-to-create-the-near-perfect-digital-calendar-state-of-the-art.html?pagewanted=all).

The majority of Pogue s article is concerning with calendar program user interfaces, and his suggestion that perhaps it is time for a paradigm shift in calendar UI s. These issues are largely the province of the creative people and companies which produce end-user calendaring products, and the consumers who will ultimately decide which paradigms to accept, and which products to adopt and/or purchase.

However, at the very end, Pogue ventures into the heart of CalConnect s territory, Finally, it goes without saying (sic) that all modern calendars should sync. To other computers. To our phones. To the web. We should never, never, ever have to enter an appointment on more than one machine.

There is more to interoperable calendaring and scheduling than just entering events only once, such as open standards which provide for a rich set of features which developers find practical to implement to produce the new UI s Pogue advocates, facilitating scheduling across disparate calendaring systems and/or machine processes, preserving data integrity and semantics across systems, to give just a few examples.

However, Pogue s almost parenthetical aside goes to the heart of a lot of it, and a lot of what CalConnect is doing today. Although CalConnect is not a formal standards development organization, virtually every important calendaring or calendaring-related standard over the last five years has been authored, edited and/or coedited by members of a CalConnect Technical Committee.

And our link:{{'/currentwork' | relative_url}}[work in progress], in areas such as open, interoperable server to server scheduling (iSCHEDULE), standardized data representations in XML and (now) JSON, calendaring web services (in collaboration with OASIS in the context of the NIST Smart Gird initiative), timezone services, improved sharing of calendars and contacts, calendar alarms and attachments, extensions to provide richer expression of public events on the web, to name some of the areas our technical committees are working in.

Whereas many of these features exist today in some products, the implementations are proprietary, or work across only selected products. This is also true in another area we are working on, consensus scheduling, which is the process whereby a group comes to agreement on when (and maybe where) to hold a meeting or carry out a task, or identifies the best time  maximizing participation, minimizing inconvenience, to schedule an event or perform a task. Consensus scheduling minimizes the overhead of achieving consensus or identifying the most favorable time(s) by allowing the potential participants to observe the responses of the other voters, and to use any scheduling flexibility they may have to adjust their response for the benefit of the entire group.

There are many excellent products in this space, and some work with some other products in a limited context, but there is no open standard which allows you to choose a product and be confident it will work with all the calendaring/scheduling products you use today, and those which you may find yourself using tomorrow.

At our next member meeting, later this month, hosted by Oracle in Santa Clara, CA, we will be holding a consensus scheduling workshop. This workshop is open to non-members and there is no fee to attend or participate.

The ProfHacker blog in the Chronicle of Higher Education has a number of entries on consensus scheduling products and concepts. These posts by George Williams are a good place to start:

http://chronicle.com/blogs/profhacker/scheduling-101-the-ideal-academic-app/22969 +
http://chronicle.com/blogs/profhacker/scheduling-101-a-few-updates-and-announcements/34823

CalConnect is truly a partnership between vendors of calendaring and scheduling systems and tools, and users of those tools¦ Although neither David Pogue, nor the New York Times, are members of CalConnect, a situation easily rectified, articles such as these not only help inform the general public, the users of these tools, but also inform the discussion and work of CalConnect and its members, and ultimately, new open standards (or changes to existing standards), and the resulting products which we will be using in the future.

Gary Schwartz +
President, CalConnect, The Calendaring and Scheduling Consortium


