---
layout: page
title: Observations from CalConnect XXIX in San Francisco
date: 2014-02-27
type: news
categories: announcements current-events general-information special-focus
excerpt: CalConnect held its twenty-ninth interoperability test event and Roundtable Technical Conference the week of February 3-7 in San Francisco, California. The event was hosted by CalConnect founding member Mozilla, which did a great job with not only the event logistics, but also making everyone feel very welcome, which was reflected in the very strong attendance at these events.
---

== Observations from CalConnect XXIX in San Francisco

[[node-182]]
Posted February 27, 2014 

CalConnect held its twenty-ninth interoperability test event and Roundtable Technical Conference the week of February 3-7 in San Francisco, California. The event was hosted by CalConnect founding member Mozilla, which did a great job with not only the event logistics, but also making everyone feel very welcome, which was reflected in the very strong attendance at these events.

36 people, representing 21 link://mbrlist.shtml[CalConnect member organizations] and one link://observer.shtml[observer], participated during the week. Almost a quarter of the attendees traveled internationally to come to CalConnect XXIX, from the Czech Republic, England, France, Hong Kong, India, New Zealand and Switzerland. Attendance at CalConnect events is growing, international membership and participation are bringing new energy and perspectives to CalConnect.

We have just published the first architectural diagrams for http://link://architectures/Task%20Architecture%200.4.pdf[Tasks] from link://tc-tasks.shtml[TC TASKS] and for link://architectures/Calendaring%20Architecture.pdf[Calendaring and Scheduling] from http://link://tc-api.shtml[TC API].

Here s what s trending from CalConnect XXIX:

*Trending  Membership*

Six of the seven new link://emergentvendor.shtml[Emergent Vendor] members (a new membership category for small vendors and startups) were represented at CalConnect XXIX, including http://milton.io/[milton.io], our newest member.

*Trending  Technical Committees (TC s) and Provisional Committees (PC s)*

* link://tc-push.shtml[TC PUSH]
+
(PUSH protocol for CalDAV and CardDAV)
* link://tc-ischedule.shtml[TC ISCHEDULE]
+
(intersystem iTIP scheduling via HTTP)
* link://tc-tasks.shtml[TC TASKS]
+
(VTODO extensions for new scheduling areas such as logistics, project and energy management)
* http://link://tc-api.shtml[TC API]
+
(Abstract API for Calendaring and Scheduling) was established from the provisional committee of the same name
* link://tc-freebusy.shtml[TC FREEBUSY]
+
Demo-ed a prototype web client supporting
+
http://tools.ietf.org/html/draft-york-vpoll-00[VPOLL]
* A Contacts Sharing Provisional Committee was established to look at developing a single standard for Contacts Sharing

*Trending  Interoperability testing*

The interoperability testing was very successful, with 23 participants from 13 organizations. The CalDAV Test Suite is rapidly being evolved into a really useful general testing tool for CalDAV servers. A more detailed accounting of the interoperability testing will be available at link://eventreports.shtml#ioptestevents[CalConnect Interoperability Test Event Reports].

*Trending  Documents/Standards*

_Much of the work in CalConnect is focused on specifications to become internet draft submissions to the IETF and ultimately be progressed to become RFCs (Proposed Standards), rather than be directly published by CalConnect itself._

*Recently published CalConnect documents:*

¢ link://architectures/Calendaring%20Architecture.pdf[Calendaring Service Architecture] +
 ¢ link://architectures/Task%20Architecture%200.4.pdf[Task Architecture V0.4] +
 ¢ link://roundtable28rpt.shtml[Report on Roundtable XXIX] +
 ¢ link://ioptestevent28rpt.shtml[Report on Interoperability Test Event XXIX] +
 ¢ link://7_things_itineraries.shtml[7 Things You Should Know About Digital Travel Itineraries] +
 ¢ link://7_things_tasks.shtml[7 Things You Should Know About Tasks]

*Recently updated internet drafts and published RFCs:*

¢ http://tools.ietf.org/html/rfc7095[jCard: The JSON Format for vCard](RFC 7095) +
 ¢ http://tools.ietf.org/html/draft-daboo-icalendar-rscale-02[Non-Gregorian Recurrence Rules in iCalendar] +
 ¢ https://tools.ietf.org/html/draft-douglass-ical-relations/[Support for iCalendar Relationships] +
 ¢ https://tools.ietf.org/html/draft-kewisch-et-al-icalendar-in-json/[jCal: The JSON format for iCalendar] +
 ¢ https://datatracker.ietf.org/doc/draft-murchison-webdav-prefer/[Use of the Prefer Header Field in Web Distributed Authoring and Versioning (WebDAV)] +
 ¢ https://tools.ietf.org/html/draft-daboo-caldav-attachments/[CalDAV Managed Attachments] +
 ¢ https://datatracker.ietf.org/doc/draft-daboo-icalendar-extensions/[New Properties for iCalendar] +
 ¢ http://tools.ietf.org/html/draft-douglass-timezone-service-10[Timezone Service Protocol] +
 ¢ http://www.ietf.org/internet-drafts/draft-daboo-calendar-%20availability-04.txt[Calendar Availability] (VAVAILABILITY) +
 ¢ http://www.ietf.org/internet-drafts/draft-douglass-calendar-%20extension-04.txt[Event Publishing Extensions to iCalendar]

*Trending  Organizationally*

To facilitate broader understanding, CalConnect has retired the name Roundtable as used for its thrice-yearly conference and members  meeting and will use the term CalConnect Conference or Conference going forward. The term Ad Hoc to describe a short-term exploratory committee has been retired, and will be replaced by Provisional Committee.

*Wrapping it all together*

CalConnect wishes to again thank Mozilla for helping to make CalConnect XXIX such a productive and enjoyable week.

At our next event, link://calconnect30.shtml[CalConnect XXX], to be hosted by AOL in Dulles, Virginia in May, we are planning to hold a public workshop on the Medical Appointment Scheduling System Contest sponsored by the Veterans Administration, with participation from the VA and from the winning team in the contest. We expect this will be a half-day workshop available to the public (by registration) and will be publishing more information as it becomes available. &nbsp;&nbsp;



Categories:&nbsp;

link:/news/announcements[Announcements]

link:/news/current-events[Current Events]

link:/news/general-information[General Information]

link:/news/special-focus[Special Focus]

