---
layout: page
title: Registration Opens for CalConnect XXX at AOL in Dulles, Virginia – May 19-23 2014
date: 2014-03-18
type: news
categories: announcements current-events general-information special-focus the-world-of-calendaring
excerpt: Registration is now open and hotel reservations are available for CalConnect XXX in Dulles, Virginia, May 19-23, 2014. The logistics page is located at link://calconnect30.shtml and contains hotel booking information, locations, meeting venue, travel information, etc.
---

== Registration Opens for CalConnect XXX at AOL in Dulles, Virginia – May 19-23 2014

[[node-181]]
Posted March 18, 2014 

Registration is now open and hotel reservations are available for CalConnect XXX in Dulles, Virginia, May 19-23, 2014. The logistics page is located at link://calconnect30.shtml and contains hotel booking information, locations, meeting venue, travel information, etc.

Our meeting venue is AOL s Steve Crane Center at 22000 AOL Way, about 2 miles from Dulles International Airport.

The Doubletree Sterling/Dulles Airport is our Conference Hotel. The hotel is about 4 miles from the airport, and runs a 24-hour shuttle between the airport and the hotel which also stops at AOL. Booking at our rate is done through AOL Travel Services; information is available via the logistics page links above.

As always, the first half of the week will be an Interoperability Test Event and the last half, starting Wednesday with lunch, will be the CalConnect Conference. In addition to the regular Technical Committee sessions and possible BOFs we expect to have report-outs from the Contacts Sharing Provisional Committee and the FSC (Federated Shared Calendar) Ad Hoc/Provisional Committee.

We are pleased to announce that there will be a special *Workshop on the VA Scheduling System* on Wednesday afternoon during the Conference, open to the public by registration and to all participants at the Interoperability Test Event and the Conference.

In late 2012, The U.S. Veterans Administration announced a prize contest to ¦encourage creation of systems that help Veterans make appointments to receive outpatient and ambulatory care from the Veterans Health Administration. and to ultimately ¦to replace the current Medical Scheduling Package (MSP) with a scheduling product which is a standards-based, modular, extensible and scalable, ¦

Recently, the winning proposals were announced. One of the winning teams has accepted our invitation to attend, and to present at, the workshop.

The workshop is to discuss health care scheduling requirements, especially in the context of the Veterans  Administration Scheduling System challenge, to examine possible changes or additions to the standards and drafts to better support the scheduling for health care.

Please contact us with any questions. We welcome observers and please note that you may register for the Workshop on Wednesday afternoon with no charge. &nbsp;

https://www.addthis.com/bookmark.php?v=300https://www.addthis.com/bookmark.php?v=300https://www.addthis.com/bookmark.php?v=300https://www.addthis.com/bookmark.php?v=300https://www.addthis.com/bookmark.php?v=300

Categories:&nbsp;

link:/news/announcements[Announcements]

link:/news/current-events[Current Events]

link:/news/general-information[General Information]

link:/news/special-focus[Special Focus]

link:/news/the-world-of-calendaring[The World of Calendaring]

