---
layout: page
title: Mimi Mugler of the University of California, Berkeley, Fourth Recipient of CalConnect Distinguished Service Award
date: 2014-05-27
type: news
categories: announcements current-events special-focus the-world-of-calendaring
excerpt: CalConnect is honored to announce that Mimi Mugler of the University of California, Berkeley, is the fourth recipient of the CalConnect Distinguished Service Award. The award was presented at CalConnect XXX on May 22, 2014.
---
:page-liquid:

== Mimi Mugler of the University of California, Berkeley, Fourth Recipient of CalConnect Distinguished Service Award

CalConnect is honored to announce that Mimi Mugler of the University of California, Berkeley, is the fourth recipient of the CalConnect Distinguished Service Award. The award was presented at CalConnect XXX on May 22, 2014.

Mimi became the University of California representative to CalConnect in early 2007, and the UC representative to the Steering Committee at the same time. She was our host for CalConnect XX in February of 2011, and she hosted the Board Strategic Planning meeting in October of 2012.

Mimi has attended every CalConnect event in North America since becoming the UC representative, and has been active on TC USECASE, and on the User SIG, which she was instrumental in starting and Chaired. She has twice served as Chair of the Steering Committee, from 2008-2010, and again from 2012-present. As Chair, she has led by building consensus in the Steering Committee, and she continuously has worked towards establishing, and furthering, a strategic direction for CalConnect and for the Steering Committee. Also as Chair of the Steering Committee, she has represented the Steering Committee to the Board of Directors, and participated at Board meetings, and at the Board Strategic Planning meeting. Mimi has been instrumental in realigning the Steering Committee structure, and working with the Steering Committee Ad Hoc on Restructuring in 2013-2014.

Mimi truly exemplifies the spirit of the award as we conceived it  commitment, collegiality, leadership and consensus building,representation of the calendaring community, and stewardship of CalConnect as an organization. We could not be more pleased to recognize and share Mimi's contributions and accomplishments in front of her peers at our 30th CalConnect conference.


