---
layout: page
title: Observations from CalConnect XXXI in Bedford, United Kingdom
date: 2014-10-20
type: news
categories: announcements current-events the-world-of-calendaring
excerpt: CalConnect held its thirty-first Conference and Interoperability Test Event the week of September 29 -- October 3, hosted by Youcanbook.me in Bedford, United Kingdom.
---
:page-liquid:

== Observations from CalConnect XXXI in Bedford, United Kingdom

Posted October 20, 2014 

CalConnect held its thirty-first Conference and Interoperability Test Event the week of September 29  October 3, hosted by http://ga.youcanbook.me[Youcanbook.me] in Bedford, United Kingdom.

The week led off with the Interoperability test Event on Monday, which had 15 participants from 9 organizations onsite, plus an additional 4 people from 3 members participating remotely. On Wednesday afternoon, the Conference opened with 19 participants from 13 members present, plus several others joining remotely for one or more sessions. Following our usual practice for European conferences, the regular Conference sessions were held largely in the afternoon, with Thursday and Friday mornings dedicated to Workshops and BoFs (Birds of a Feather sessions).

Here's what's trending from CalConnect XXXI:

*Trending  Membership*

In the weeks immediately preceding CalConnect XXXI, two organizations joined CalConnect, raising the total to four new members since our May event.

* http://burbio.com[Burbio]
+
, based in Burbio, based in Pelham, New York, offers a calendar sharing and synchronization platform built for local communities such as suburban towns.
* http://smoothsync.org/test[SmoothSync]
+
, based in Dresden, Germany, offers a synchronization tool for Android apps syncing with iCloud and Yahoo.

*Trending  Technical Committees (TC s) and Provisional Committees (PC s)*

* link:{{'/tc-freebusy' | relative_url}}[TC FREEBUSY]
+
provided a live demo of a VPOLL (consensus scheduling) client, and expects to be able to demonstrate multiple clients and servers at the next CalConnect Event featuring multiple implementations each on its own server via iSCHEDULE (server-server scheduling).
* link:{{'/tc-fsc' | relative_url}}[TC FSC]
+
(Federated Shared Calendars) and
+
link:{{'/tc-sharing' | relative_url}}[TC SHARING]
+
(Contacts and Calendar Sharing for CalDAV and CardDAV) were formed from the Contacts Sharing and FSC Provisional Committees at the end of the last event, and offered their first sessions as Technical Committees at this event.

*Trending  Interoperability testing*

The interoperability testing was very successful, with 15 participants onsite from 9 members; additionally 4 people from 3 members attended the test event remotely. As always much testing of various CalDAV features. Some new implicit scheduling implementations testing against clients. TC IOPTEST will start building a list of areas to test next time immediately  starting early may help to provide some specific implementation goals. In particular we hope to have initial implementations of the PUSH specifications being developed by TC PUSH.. A more detailed accounting of the interoperability testing is available at link:{{'/eventreports#ioptestevents' | relative_url}}[CalConnect Interoperability Test Event Reports].

*Trending  Special Events*

Two Workshops were held on Thursday morning and Friday morning: Groups Scheduling and Sharing and History and Comment Feeds in iCalendar. A Birds of a Feather session on developing a unified Calendaring & Scheduling Architecture was also held on Friday. All three subjects seem likely to result in new work areas for CalConnect, and will probably be returned to at the next event for further exploration.

*Trending  Documents, Specifications and Standards*

Much of the work in CalConnect is focused on specifications to be submitted as internet drafts to the IETF with the goal of helping progressing them to become RFCs (Proposed Standards); other work is published directly by CalConnect itself or submitted to other standards organizations.

*Published documents* :

* link:{{'/conference31rpt' | relative_url}}[Report on CalConnect Conference XXXI]
* link:{{'/7_things_api' | relative_url}}[7 Things You Should Know About the Abstract Calendaring API]
* link:{{'/starterlistcaldavcarddav' | relative_url}}[Updated Starter List of CalDAV and CardDAV Standards and Specifications]

*CalConnect internet drafts adopted for progression via IETF Working Groups*:

* http://datatracker.ietf.org/doc/draft-ietf-tzdist-caldav-timezone-ref/[CalDAV: Timezones by Reference]
* http://datatracker.ietf.org/doc/draft-ietf-tzdist-caldav-timezone-ref/[Time Zone Data Distribution Service]
* https://datatracker.ietf.org/doc/draft-ietf-calext-rscale/[Non-Gregorian Recurrence Rules in iCalendar]

*Updated internet drafts and published RFCs*:

* http://tools.ietf.org/html/rfc7265[jCal: The JSON Format for iCalendar]
+
(RFC 7265)
* http://datatracker.ietf.org/doc/draft-douglass-ical-relations/[Support for iCalendar Relationships]
* https://datatracker.ietf.org/doc/draft-york-vpoll/[VPOLL: Consensus Scheduling Component for iCalendar]
* http://tools.ietf.org/html/draft-daboo-icalendar-extensions[New Properties for iCalendar]
* http://datatracker.ietf.org/doc/draft-murchison-webdav-prefer/[Use of the Prefer Header Field in Web Distributed Authoring and Versioning (WebDAV)]

*Trending  Organizationally*

Mike Douglass of Rensselaer Polytechnic Institute was the fifth recipient of the link:{{'/dsa' | relative_url}}[CalConnect Distinguished Service Award]. Mr. Douglass has been active in CalConnect since 2005, and currently serves as the Chair of TC EVENTPUB, TC IOPTEST, TC TIMEZONE, and the co-Chair of TC FREEBUSY, in addition to being the CalConnect Interoperability Test Manager since 2011.

*Wrapping it all together*

CalConnect wishes to again thank Youcanbook.me for helping to make CalConnect XXXI such a productive and enjoyable week, and to the organizations who participated in the event. Youcanbook.me did an outstanding job with event logistics, hosting our conference at The Higgins Museum in Bedford, a departure from our usual conference rooms at member facilities or the occasional hotel, and we enjoyed The Higgins and its onsite caterers and restaurant The Pantry very much.

The next CalConnect event will take place January 26-30, 2015 in San Jose, California,hosted by http://www.kerio.com[Kerio Technologies]. We ll be posting more information about this event going forward, and we invite you to join us and learn more about what we are doing moving forward.


