---
layout: page
title: CalConnect -- The Calendaring and Scheduling Consortium -- is returning to Europe this autumn
date: 2014-07-17
type: news
categories: announcements current-events general-information the-world-of-calendaring
excerpt: Our first three European conferences, in 2011, 2012, and 2013, were very successful, and our European colleagues encouraged us to return again this autumn. Therefore, CalConnect XXXI will take place in Bedford, United Kingdom, on September 29 -- October 3, 2014, hosted by Youcanbook.me.
---
:page-liquid:

== CalConnect -- The Calendaring and Scheduling Consortium -- is returning to Europe this autumn

Our first three European conferences, in 2011, 2012, and 2013, were very successful, and our European colleagues encouraged us to return again this autumn. Therefore, link:{{'/calconnect31' | relative_url}}[CalConnect XXXI] will take place in Bedford, United Kingdom, on September 29  October 3, 2014, hosted by https://ga.youcanbook.me[Youcanbook.me].

We encourage our European colleagues and others interested in Calendaring and Scheduling to join us. We re working to make this event as attractive as possible to organizations that are not currently members but have thought about exploring CalConnect, and a European event is a chance for people to participate in a CalConnect event without having to incur the travel costs and time of coming to North America.

CalConnect is a collaboration between calendaring and scheduling vendors and users. It was established to further interoperability between calendaring and scheduling implementations, and works towards this purpose by driving the evolution of calendaring and scheduling standards through technical committee work, holding regular interoperability testing events, and hosting regular conferences, workshops and symposia focused on calendaring and scheduling.

European companies were among CalConnect's earliest members, and as standards and interoperability are both central to CalConnect's mission and are strong core values of European Information Technology, we have long recognized the importance of increasing European involvement in CalConnect. To that end we held special events in Europe in 2007 and 2008 in preparation for our first regular CalConnect conference in Europe in 2011. This autumn's event in Bedford is one which we hope will continue with even greater European participation in CalConnect's interoperable calendaring and scheduling efforts, and we applaud the increased involvement by Europeans in our technical activities over the last few years.

*Overview*

Our venue will be http://www.thehigginsbedford.org.uk/[The Higgins Art Gallery and Museum] in Bedford, located on Castle Lane, Bedford, Mk40 3XD United Kingdom. The Higgins is a short walk from the Conference Hotel, http://www.bedfordswanhotel.co.uk/[The Bedford Swan], and other accommodation alternatives, All events of the CalConnect week, September 29  October 3, except for the Monday Test Event dinner, the Wednesday Reception, and the Thursday Conference dinner will take place at the Higgins. Full information about the conference may be found at link:{{'/calconnect31' | relative_url}}[CalConnect XXXI] including the week's schedules, registration, and logistics information.

Bedford is about 50 miles north of London; we recommend European travelers who arrive by air to arrive at Luton Airport (north of London) as it is nearest. Travelers from further away will probably arrive at London Heathrow or London Gatwick. Information on getting from the airports to Bedford is available via the link:{{'/calconnect31' | relative_url}}[CalConnect XXXI] page.

Monday, Tuesday, and Wednesday morning, September 29  October 1, will be our Interoperability Test Event, ending with lunch on Wednesday. Wednesday afternoon (beginning with lunch), Thursday, and Friday, October 1-3, will be the Calconnect Conference which will include workshops, and technical committee sessions: briefings on what the CalConnect technical committees are doing, and discussions of problems, alternatives, and participation in the work of the Technical Committees.

*Registration and Fees*

You must register separately for the Interoperability Test Event and the CalConnect Conference. Please see link:{{'/regtypes' | relative_url}}[Registration and Fees] for more information and registration forms.

Special Registration Fee for This Event: $600 USD per person for first-time non-members to cover both the Interoperability Test Event and the CalConnect Conference.

We encourage you to register as soon as possible. Upon registration you will be invoiced for the amount due. However, you may choose to pay later, including at the event, if it is more convenient.

*Conference Hotel*

Our conference hotel is http://www.bedfordswanhotel.co.uk/[The Bedford Swan Hotel], The Embankment, Bedford. You may book the hotel directly from its website. There is no fixed rate and the rates will probably rise as we get closer to the event, so we recommend booking as soon as you know your travel plans. A list of alternative accommodations is linked from the link:{{'/calconnect31' | relative_url}}[CalConnect XXXI] web page, should the Swan not be available or you prefer different arrangements.


*Who and What is CalConnect?*

We are a collaboration between calendaring and scheduling vendors and users, established to further interoperability between calendaring and scheduling implementations, and work towards this purpose by driving the evolution of calendaring and scheduling standards through technical committee work, holding regular interoperability testing events, and hosting regular conferences, workshops and symposia focused on calendaring and scheduling. See our current member list at link:{{'/mbrlist' | relative_url}}[CalConnect Members]. Learn more about CalConnect at our link:{{'/' | relative_url}}[website] and our link:{{'/blog' | relative_url}}. Find out about our previous events from our link:{{'/eventreports' | relative_url}}[Event Reports] and from posts on our blog. You can find out more about membership in CalConnect at link:{{'/membership' | relative_url}}[CalConnect Membership].

*What is CalConnect currently focused on?*

You may find brief descriptions of the current work items of our Technical Committees at link:{{'/currentwork' | relative_url}}[Current Work].

Questions and Feedback:

Please contact us at mailto:contact@calconnect.org[contact@calconnect.org] with questions or feedback.

In particular, if you are interested in the Interoperability Test event and would like to suggest specific areas of testing, or potential participants, we want to know. If you have specific areas of interest or topics which you would like to see addressed in the workshops and symposia, please let us know about that as well! Also, feel free to send this e-mail on to others who you feel might be interested, or contact us and ask us to invite them as well.

You are also welcome to contact me directly with questions and suggestions.

Please join us in Bedford!

mailto:dave.thewlis@calconnect.org[Dave Thewlis] +
Executive Director +
The Calendaring and Scheduling Consortium

--

*More Information:*

More information about the test event, the technical conference, and the workshops may be found below. The schedule for the week may be viewed at link:{{'/calconnect31#schedule' | relative_url}}[CalConnect XXXI Schedule] (at this early date the schedule is an outline; we have not yet assigned time slots to specific sessions. This should happen in the next few weeks.) The entire set of logistics information, including travel, hotel booking, schedule, and as we get closer to the event, topical agendas and final topics for the workshops and symposia, may be viewed at link:{{'/calconnect31' | relative_url}}[CalConnect XXXI].

*Interoperability Testing*

The Interoperability Testing will take place Monday and Tuesday, September 29-30, plus Wednesday morning October 1st. Our interoperability test events offer those with calendaring implementations a chance to test against others one-on-one; the event is structured to allow "`testing pairs`" where you will get a chance to test with everyone in the course of event.

The exact testing scenarios will be decided based on who is coming and what (and with whom) they want to test. As of today we will definitely plan to test at least the following areas:

* jCal (The JSON format for iCalendar)
* RSCALE (Non-Gregorian Calendar Recurrences)
* Calendar sharing
* VPOLL Support in clients and servers
* Scheduling
* VAVAILABILITY
* CalDAV
* iCalendar/iMIP/iTIP and iMIP gateways
* iSchedule
* CardDAV
* Timezone Service Protocol
* Managed Attachments
* VAVAILABILITY
* If there is interest, synchronization testing for mobile clients in general
* Informal workshop on the CalDAV Tester Test Suite

Please see link:{{'/iop1409' | relative_url}}[CalConnect XXXI Interoperability Test Event] for more information.

+
*Technical Workshops and Symposia*

Thursday and Friday mornings will be dedicated to workshops and symposia, which are included in the Conference Registration. The specific events are in the early planning stages; the link:{{'/calconnect31#schedule' | relative_url}}[CalConnect XXXI Schedule] will reflect more detail as soon as we have it.

*CalConnect Conference*

At each CalConnect event, the Conference offers an opportunity for each of the CalConnect Technical Committees and Provisional Committees to present its work, invite suggestions, and conduct open discussions with the attendees on issues or topics under deliberation in the committee. In order to facilitate people in North America joining the Roundtable portion of the week's events, the Conference sessions will be held Wednesday, Thursday and Friday afternoons. The Conference covers (at least)

* Opening and introduction to CalConnect
* Report from the Interoperability Test Event
* Technical Committee sessions for all CalConnect TCs and PCs
* Opportunities for BOFs ("`birds of a feather`" discussions)
* Final wrapup and summary of all sessions
* New initiatives
* CalConnect Plenary Session

The conference will conclude no later than 18:00 on Friday, October 3rd.

In addition to the formal agenda there will be plenty of opportunity for networking and informal discussions with the leading experts in Calendaring and Scheduling applications, systems, and specifications.

*Social Events*

There will be a dinner for all Interoperability Test Event participants on Monday Evening, a Reception on Wednesday evening for all participants in either the Test Event and/or the Conference, and a dinner for all Conference participants on Thursday evening. The social events are included in your registration fee.

*Meals*

Your registration to the Interoperability Test Event or the Conference includes lunch and morning and afternoon refreshments for the period of the event, plus the reception Wednesday evening. In addition, registration to the test event includes the Monday evening IOP test event dinner, and registration to the technical conference includes the Thursday evening Conference. Please note that breakfast is not included as it is generally included with your hotel package.

