---
layout: page
title: Registration is open for CalConnect XXXV at AOL in Palo Alto, California, January 11-15, 2016
date: 2015-11-03
type: news
categories: announcements current-events general-information
excerpt: Registration is now open and hotel reservations may be made for CalConnect XXXV in Palo Alto, California, January 11-15, 2016, hosted by AOL.
---
:page-liquid:

== Registration is open for CalConnect XXXV at AOL in Palo Alto, California, January 11-15, 2016

Posted November 3, 2015 

Registration is now open and hotel reservations may be made for CalConnect XXXV in Palo Alto, California, January 11-15, 2016, hosted by AOL.

The CalConnect XXXV web page is located at link:{{'/calconnect35' | relative_url}}[/calconnect35] and contains hotel information and booking, airport and transfer information, meeting venue, international travel information, etc.

We have moved the event forward two weeks because the Superbowl will be in Santa Clara in early February, which means that hotel bookings are already getting difficult and rates are going up even for our new dates of 11-15 January. Therefore, if you are planning or considering coming to this event we strongly encourage you to book your hotel as soon as possible! And you are encouraged to register at the same time.

The conference hotel is http://www.dinahshotel.com/[Dinah's Garden Hotel] in Palo Alto. The hotel is offering an AOL rate of $240 per night, however that may depend on availability as the hotels in the area are already filling up and raising their rates. The conference hotel is about 1.5 miles from AOL's headquarters at 395 Page Mill Road, Palo Alto, California 94306. The web page for the event also lists other hotels which may or may not offer an AOL rate during our target week.

We will be at AOL's headquarters for the entire week, as noted above at 395 Page Mill Road, about 1.5 miles from the conference hotel.

Please note that, to obtain the AOL rate at the Conference Hotel, you cannot book online. The event web page offers telephone numbers for the hotel; please call the hotel to book, and say you want the AOL rate.

A preliminary schedule for the week ss posted on the event web page. The interoperability test event will take place Monday, Tuesday, and Wednesday morning; the Conference will be Wednesday afternoon through Friday. We will be using our new format for the conference; most conference sessions will be higher-level strategy and cross-TC, with some specific very detailed discussions held during the interoperability test event. We expect that the schedule and program will evolve over time, so check the web page periodically. The conference program has not been determined as yet so only an outline of meal and break times is available. We will announce immediately when the conference program has been finalized.


