---
layout: page
title: Only a week until CalConnect XXXII and our 10th Anniversary Celebration
date: 2015-01-19
type: news
categories: announcements current-events special-focus the-world-of-calendaring
excerpt: CalConnect XXXII is next week — January 26-30, in San Jose, California. And the 10th anniversary celebration is Wednesday the 28th from noon to six, with a reception to follow. No fee is required to attend the 10th anniversary celebration, but you do have to register so we know how many are coming! See CalConnect 10th Anniversary Celebration for more information, the basic schedule, and a link to the registration page. Space has become limited, so register soon if you plan to come!
---
:page-liquid:

== Only a week until CalConnect XXXII and our 10th Anniversary Celebration

Posted January 19, 2015 

CalConnect XXXII is next week  January 26-30, in San Jose, California. And the 10th anniversary celebration is Wednesday the 28th from noon to six, with a reception to follow. No fee is required to attend the 10th anniversary celebration, but you do have to register so we know how many are coming! See link:{{'/tenthanniversary' | relative_url}}[CalConnect 10th Anniversary Celebration] for more information, the basic schedule, and a link to the registration page. Space has become limited, so register soon if you plan to come!

For more info about the entire CalConnect week including the interoperability testing (first part of the week) and the conference itself (Thursday and Friday) see link:{{'/calconnect32' | relative_url}}[CalConnect XXXII].

See you in San Jose!


