---
layout: page
title: Registration Open for CalConnect XXXVIII in Irvine, California, February 13-17, 2017
date: 2016-11-14
type: news
categories: announcements current-events general-information
excerpt: Registration is now open and hotel rooms may be booked for CalConnect XXXVIII Irvine, California, February 13-17, 2017, hosted by the University of California, Irvine.
---

== Registration Open for CalConnect XXXVIII in Irvine, California, February 13-17, 2017

[[node-424]]
Posted November 14, 2016 

Registration is now open and hotel rooms may be booked for CalConnect XXXVIII Irvine, California, February 13-17, 2017, hosted by the http://www.uci.edu/[University of California, Irvine]. +
 +
 The CalConnect XXXVIII web page is located at https://www.calconnect.org/events/calconnect-xxxviii-february-13-17-2017 and contains hotel information and booking, airport and transfer information, meeting venue, international travel information, etc. &nbsp; +
 +
 The&nbsp; meeting venue is the UCI Conference Center, located in the Student Center building.&nbsp; It is within a few miles of the conference hotel. The Conference Hotel is the Hotel Irvine&nbsp; which is also within a few miles of the nearest airport, Johne Wayne Airport (SNA). We are offered a special UCI rate of $153 for most nights (Friday and Saturday are $119), which includes breakfast. &nbsp; +
 +
 The Interoperability Test Event and Developers Forum will take place on our usual schedule beginning Monday morning and going through Wednesday noon.&nbsp; The Conference will begin Wednesday after lunch and run through Friday afternoon. &nbsp; +
 +
 We will be posting schedules and agenda as soon as possible on the event web page, and expect that they may evolve over time.



Categories:&nbsp;

link:/news/announcements[Announcements]

link:/news/current-events[Current Events]

link:/news/general-information[General Information]

