---
layout: page
title: CalDAV and CardDAV Protocol/Implementations Websites Superceded
date: 2016-10-14
type: news
categories: announcements current-events general-information special-focus the-world-of-calendaring
excerpt: For some time CalConnect has supported two protocol and implementation oriented sites, caldav.calconnect.org and carddav.calconnect.org. These sites provides some information about the protocols themselves but their primary purpose has been to list implementations of the protocols (client, server, libraries, services). As the non-implementation sections of these sites duplicate information available elswehere, CalConnect has migrated the implementations information to the CalDAV and CardDAV sections of the new CalConnect Calendar Developers Guide. Information is also provided on how to contribute, or provide feedback, for those wishing to have their implementations added to the Guide.
---
:page-liquid:

== CalDAV and CardDAV Protocol/Implementations Websites Superceded

For some time CalConnect has supported two protocol and implementation oriented sites, http://caldav.calconnect.org[caldav.calconnect.org] and http://carddav.calconnect.org[carddav.calconnect.org]. These sites provides some information about the protocols themselves but their primary purpose has been to list implementations of the protocols (client, server, libraries, services). As the non-implementation sections of these sites duplicate information available elswehere, CalConnect has migrated the implementations information to the CalDAV and CardDAV sections of the new http://devguide.calconnect.org[CalConnect Calendar Developers Guide]. Information is also provided on how to contribute, or provide feedback, for those wishing to have their implementations added to the Guide.

The URLs now point to single pages with links within the Developers Guide for each category of implementation, and also a link to the How To Contribute section of the Guide. We anticipate that we will maintain these two domains for some time as a convenience for those searching for CalDAV or CardDAV implementations. Please direct new implemention entries or inquiries to the http://devguide-calconnect.rhcloud.com/How-to-Contribute[Developers Guide How to Contribute] page.




