---
layout: page
title: VAVAILABILITY (Calendar Availability) Announced as RFC 7953
date: 2016-08-17
type: news
categories: announcements current-events general-information special-focus the-world-of-calendaring
excerpt: The IETF has announced that VAVAILABILITY, a CalConnect specification submitted to the IETF, has been approved and published as RFC 7953.
---

== VAVAILABILITY (Calendar Availability) Announced as RFC 7953

[[node-408]]
Posted August 17, 2016 

The IETF has announced that VAVAILABILITY, a CalConnect specification submitted to the IETF, has been approved and published as RFC 7953.

VAVAILABILITY is a new iCalendar (https://tools.ietf.org/html/rfc5545[RFC 5545]) component that allows the publication of available and unavailable time periods associated with a calendar user, extending basic free-busy lookups to generate repeating blocks of available or busy time with exceptions as needed.

RFC 7953, Calendar Availability (VAVAILABILITY),&nbsp; https://tools.ietf.org/html/rfc7953 was developed by the FREEBUSY and other Technical Committees.&nbsp; Following submission to the IETF it was subsequently adopted by the IETF CALEXT workng group and progressed to final submission.&nbsp;

CalConnect contratulates everyone who participated in this work over the years since its inception, and everyoine who participated in the CALEXT Working Group at the IETF.

&nbsp;



Categories:&nbsp;

link:/news/announcements[Announcements]

link:/news/current-events[Current Events]

link:/news/general-information[General Information]

link:/news/special-focus[Special Focus]

link:/news/the-world-of-calendaring[The World of Calendaring]

