---
layout: page
title: Registration Open for CalConnect XXXVII in Dresden, September 12-16, 2016
date: 2016-06-27
type: news
categories: announcements current-events general-information
excerpt: Registration is now open and hotel rooms may be booked for CalConnect XXXVII Dresden, September 12-16, 2016, hosted by dmfs (SmoothSync).
---
:page-liquid:

== Registration Open for CalConnect XXXVII in Dresden, September 12-16, 2016

Registration is now open and hotel rooms may be booked for CalConnect XXXVII Dresden, September 12-16, 2016, hosted by http://smoothsync.org/[dmfs (SmoothSync)].

The CalConnect XXXVII web page is located at link:{{'/events/calconnect-xxxvii-september-12-16-2016' | relative_url }} and contains hotel information and booking, airport and transfer information, meeting venue, international travel information, etc.

The conference hotel and meeting venue is http://www.schloss-eckberg.de/en/[Schloss Eckberg], Bautzner Straße 134, 01099 Dresden, Germany. The Schloss is on a hill next to the river Elbe, and is a short tram ride from the center of Dresden. As noted under the Lodging section of the web page, you will have to book by e-mail or telephone call to get the special "`CalConnect`" rate.

The Interoperability Test Event and Developers Forum will take place on our usual schedule beginning Monday morning and going through Wednesday noon. The Conference will begin Wednesday after lunch and run through Friday afternoon.  We will be posting schedules as soon as possible on the event web page, and expect that they may evolve over time.
