---
layout: page
title: Only four weeks to CalConnect XXXVIII at University of California Irvine
date: 2017-01-16
type: news
categories: announcements current-events general-information special-focus
excerpt: It's now only four weeks until CalConnect XXXVIII at UC Irvine - and two weeks until early registration closes and the registration fee increases.
---
:page-liquid:

== Only four weeks to CalConnect XXXVIII at University of California Irvine

It's now only four weeks until CalConnect XXXVIII at UC Irvine - and two weeks until early registration closes and the registration fee increases.

https://www.calconnect.org/events/calconnect-xxxviii-february-13-17-2017

https://www.calconnect.org/events/event-registration-payment

The agenda and sessions for the Conference and Test Event / Developers  Forum are posted on the web page:

https://www.calconnect.org/events/calconnect-xxxviii-february-13-17-2017#test-schedule

https://www.calconnect.org/events/calconnect-xxxviii-february-13-17-2017#conference-schedule

*We have highlighted two conference sessions* of particular interes::

1600-1700 on Wednesday, 15 February:

*TC VCARD, ISO TC 211, and ISO 19160* +
This session will review the charter, goals and problems facing the evolution of VCARD envisioned by the TC; report on the establishment of a liaison with ISO TC 211; and review ISO 19160 and its applicability to the work of the TC. Discussion will focus on the issues the TC may face in incorporating ISO 19160 elements into VCARD, and how (and if) expanded structured address formats can be made backward compatible. TC VCARD.

*1100-1230 on Thursday, 16 February:*

*Calendar Spam and potential best practices* +
One or more presentations from members who are actively dealing with calendar spam issues, general discussion, formulation of recommendations. Under consideration are iMIP issues; odd content types; DKIM and SPF; alarms and notifications; converting other content into events.



As always, non-members may attend a CalConnect Conference as link:{{'/events/events-activities/observers' | relative_url }}[Observers].



Please join us in Irvine!


