---
layout: page
title: Registration is now open  for CalConnect XLIII in Karlsruhe, Germany, September 24-27, 2018, hosted by 1&1
date: 2018-07-24
type: news
categories: announcements current-events the-world-of-calendaring
excerpt: The CalConnect XLIII web page contains lodging information, airport and transfer information, meeting venue, schedule, etc.
---
:page-liquid:

== Registration is now open  for CalConnect XLIII in Karlsruhe, Germany, September 24-27, 2018, hosted by 1&1

Posted July 24, 2018

The CalConnect XLIII web page is located at link:{{'/events/calconnect-xliii-september-2018' | relative_url}}[/events/calconnect-xliii-september-2018] and contains lodging information, airport and transfer information, meeting venue, schedule, etc. Note that international travelers will probably want to fly into Frankfurt Airport (FRA) and take the 1-hour train ride to Karlsruhe; see link:{{'/events/calconnect-xliii-september-2018#transportation' | relative_url}}[/events/calconnect-xliii-september-2018#transportation] for more information.

The meeting venue is at the 1&1 facilities in Karlsruhe, at Ernst-Frey-Straße 10, 76135 Karlsruhe, Germany. The venue is less than a kilometer walk from the conference hotel, http://www.hotel-santo.de/[Hotel Santo], Karlstraße 67-69, 76137 Karlsruhe, Germany.

The hotel may be booked immediately, see link:{{'/events/calconnect-xliii-september-2018#lodging' | relative_url}}[/events/calconnect-xliii-september-2018#lodging] for more information and information. You must book by the end of August to receive the CalConnect rate, and you must book via the e-mail address provided on this Lodging page.

This event is the first preview of our new conference format. CalConnect XLIII will be four days (Monday through Thursday), and brings together, as a single event and with a single fee, our traditional conference (Conference Track), with elements of the former developers' forum (Technical Track). The two tracks are simply a handy guide to the session content, and all attendees are encouraged to attend sessions in both tracks. We will use your feedback and experience at Karlsruhe to help us fine-tune our new conference for events in 2019 and beyond.

Please see the introduction on the event web page linked above for a fuller description of what the event will look lie.

The schedule for the four days is available on the event web page at link:{{'/events/calconnect-xliii-september-2018#conference-schedule' | relative_url}}[]. We do expect that the schedule will evolve as we get closer to the event, so please check periodically.

Fees and Registration Options: The registration fee for the full four-day event is $800 (late registration is $900. We are also offering a trial one-day registration fee of $300 (late registration $375). Registration information is at link:{{'/events/event-registration-payment' | relative_url }} and is linked from the event web page.

As always, please let me know if you have any questions.

See you in Karlsruhe!


