---
layout: page
title: ﻿Ribose wins Six Gold, Silver and Bronze Stevie® Awards at 2018 International Business Awards®
date: 2018-08-23
type: news
categories: announcements current-events member-news special-focus
excerpt: From BusinessWire
---

== ﻿Ribose wins Six Gold, Silver and Bronze Stevie® Awards at 2018 International Business Awards®

[[node-487]]
Posted August 23, 2018 

From BusinessWire:

http://www.ribose.com[Ribose] has won four Gold Stevie Awards for Best New Semantic Technology Platform, Tools and Applications, Best New International Data Protection Solution, Best New Collaboration/Social Networking Solution and Best New Scholarly Publishing Information Solution categories, as well as a Silver Stevie for Most Innovative Tech Company of the Year - Up to 100 Employees and a Bronze Stevie for Technical Innovation of the Year - At Organizations With Up to 100 Employees at The 15th Annual International Business Awards.&nbsp; The International Business Awards are the world s premier business awards program, where all individuals and organizations worldwide are eligible to submit nominations. The 2018 IBAs received more than 3,900 entries from 74 nations and territories, from organizations of all sizes and in virtually every industry

Ribose also won recognition for conceiving and developing Metanorma  a standard for standards documents  for use by international standardization bodies such as CalConnect and ISO to achieve an end-to-end, author-to-print workflow...This year s IBA judges also lauded Ribose s development of Metanorma as a revolutionary concept, noting that, Setting standards for standardization is a very important requirement. This is a great initiative. Another judge remarked, To anyone who has to administrate such standards, this [Metanorma] will seem like a godsend.

The complete report is at https://www.businesswire.com/news/home/20180822005221/en/Ribose-wins-Gold-Silver-Bronze-Stevie%25C2%25AE-Awards

&nbsp;

https://www.addthis.com/bookmark.php?v=300https://www.addthis.com/bookmark.php?v=300https://www.addthis.com/bookmark.php?v=300https://www.addthis.com/bookmark.php?v=300https://www.addthis.com/bookmark.php?v=300

Categories:&nbsp;

link:/news/announcements[Announcements]

link:/news/current-events[Current Events]

link:/news/member-news[Member News]

link:/news/special-focus[Special Focus]

