---
layout: page
title: Registration is now open  for the CalConnect Virtual Conference 2021, April 12-15, 2021
date: 2020-12-08
type: news
categories: the-world-of-calendaring current-events announcements
excerpt: The CalConnect Virtual Conference 2021 web page  contains information about the timing, structure, and sessions offered for this virtual conference.  .
---

== Registration is now open  for the CalConnect Virtual Conference 2021, April 12-15, 2021

[[node-537]]
Posted December 8, 2020 

The https://www.calconnect.org/events/calconnect-virtual-conference-2020[CalConnect Virtual Conference 2021 web page]&nbsp; contains information about the timing, structure, and sessions offered for this virtual conference.&nbsp; .

The CalConnect Conference is planned for four days, Monday-Thursday, April 12-15, with the possibility of scheduling additional working sessions or testing on Friday April 16.

The conference will be held via Zoom and we expect will last approximately 3-3.5 hours each day.&nbsp; Monday through Wednesday will be scheduled from 1100 to 1400 Eastern Standard Time.&nbsp; Thursday will be scheduled for our Asia/Pacific members and will begin at 0100 Eastern Standard Time.

Please see the link://events/calconnect-virtual-conference-2020[CalConnect Virtual Conference 2021 web page] for more information, including the planned schedule for the event.

Fees and Registration Options:&nbsp; The registration fee for the conference is $50 per person for members and non-members alike.&nbsp;&nbsp; Registration information is at https://www.calconnect.org/events/event-registration-payment and is linked from the event web page.&nbsp; Please note that all registrations must be paid in advance of the conference.

Event access information and credentials will be e-mailed to all registered participants late in the week prior to the conference.&nbsp; You must be registered to attend the event.

https://www.addthis.com/bookmark.php?v=300https://www.addthis.com/bookmark.php?v=300https://www.addthis.com/bookmark.php?v=300https://www.addthis.com/bookmark.php?v=300https://www.addthis.com/bookmark.php?v=300

Categories:&nbsp;

link:/news/the-world-of-calendaring[The World of Calendaring]

link:/news/current-events[Current Events]

link:/news/announcements[Announcements]

