---
layout: page
title: CalConnect Nottingham Rescheduled to October 18-22, 2021
date: 2020-10-25
type: news
categories: the-world-of-calendaring general-information current-events announcements
excerpt: The CalConnect Nottingham Conference has been rescheduled again, to October 18-22, 2021.  All other arrangements (host, venue, conference hotel) remain unchanged.  The Board has reached this decision after reviewing the current status of the pandemic, as available from the WHO and CDC, and concluded that the chance of having a successful in-person conference before mid-2021 is still very slim.
---

== CalConnect Nottingham Rescheduled to October 18-22, 2021

[[node-535]]
Posted October 25, 2020 

The CalConnect Nottingham Conference has been rescheduled again, to October 18-22, 2021.&nbsp; All other arrangements (host, venue, conference hotel) remain unchanged.&nbsp; The Board has reached this decision after reviewing the current status of the pandemic, as available from the WHO and CDC, and concluded that the chance of having a successful in-person conference before mid-2021 is still very slim.

We recommend that those planning to attend the Nottingham meeting avoid non-changeable travel arrangements until we can confirm when the meeting will be held. You can of course still register for the meeting, and can defer registration payment until the meeting.

Our apologies for the inconvenience and uncertainty.&nbsp; We hope the Nottingham meeting in October 2021 will be possible to hold, and hope to see you there.



Categories:&nbsp;

link:/news/the-world-of-calendaring[The World of Calendaring]

link:/news/general-information[General Information]

link:/news/current-events[Current Events]

link:/news/announcements[Announcements]

