---
layout: page
title: CalConnect XLVII Rescheduled to June 15-19 2020
date: 2020-02-28
type: news
categories: the-world-of-calendaring special-focus current-events announcements
excerpt: The CalConnect XXVII meeting in Nottingham is now rescheduled from April 20-24 to the week of June 15-19 2020.  All other arrangements (host, venue, conference hotel) remain unchanged.  The Board has reached this decision after reviewing the current status of COVID-19, as available from the WHO and CDC.
---

== CalConnect XLVII Rescheduled to June 15-19 2020

[[node-519]]
Posted February 28, 2020 

The CalConnect XXVII meeting in Nottingham is now rescheduled from April 20-24 to the week of June 15-19 2020.&nbsp; All other arrangements (host, venue, conference hotel) remain unchanged.&nbsp; The Board has reached this decision after reviewing the current status of COVID-19, as available from the WHO and CDC.

As the situation worldwide with respect to the virus is changing rapidly, please note that we might have to reschedule again to the September/October timeframe.&nbsp; We will issue an update no later than mid-April as to our status.

We recommend that those planning to attend the Nottingham meeting avoid non-changeable travel arrangements, at least until after our further update in mid-April.&nbsp; You can of course still register for the meeting, and can defer registration payment until the meeting.

Our apologies for the inconvenience and uncertainty.&nbsp; We hope the Nottingham meeting in June will proceed apace.



Categories:&nbsp;

link:/news/the-world-of-calendaring[The World of Calendaring]

link:/news/special-focus[Special Focus]

link:/news/current-events[Current Events]

link:/news/announcements[Announcements]

