---
layout: page
title: Registration is now open for CalConnect XLVII in Nottingham, United Kingdom, April 20-24, 2020, hosted by Cronofy
date: 2020-01-07
type: news
categories: the-world-of-calendaring special-focus current-events announcements
excerpt: The CalConnect XLVII web page contains lodging information, airport and transfer information, and meeting venue.
---

== Registration is now open for CalConnect XLVII in Nottingham, United Kingdom, April 20-24, 2020, hosted by Cronofy

Posted January 7, 2020 

The https://www.calconnect.org/events/calconnect-xlvii-april-20-24-2020[CalConnect XLVII web page] contains lodging information, airport and transfer information, and meeting venue.

The CalConnect Conference itself will be four days, Monday-Thursday, April 20-23. Friday April 24th will be a joint work and testing day if some attendees with to stay through Friday.

The meeting venue is the https://antenna.uk.com/[Antenna Media Centre], 9A Beck Street, in central Nottingham. The Conference Hotel is the https://all.accor.com/hotel/6160/index.en[ibis Nottingham Centre], 16 Fletcher Gate, a short walk from the train station and the meeting venue. The hotel may be booked immediately; there is no special rate so book through their website.&nbsp;

Please see the introduction on the https://www.calconnect.org/events/calconnect-xlvii-april-20-24-2020[CalConnect XLVII web page] for a fuller description of the event.&nbsp;

The schedule for the four days is currently under development. We will post an initial schedule as soon as possible and announce it to these lists. We will also issue a call for requests for additional sessions.

Fees and Registration Options: The registration fee for the full four-day event is $950 (late registration is $1050. We are also offering a one-day registration fee of $400 (late registration $475).&nbsp; Registration information is at https://www.calconnect.org/events/event-registration-payment and is linked from the event web page.

As always, please https://www.calconnect.org/contact[contact us] if you have any questions.&nbsp;


