---
layout: page
title: CalConnect XLVII Rescheduled to October 12-16, 2020
date: 2020-04-12
type: news
categories: the-world-of-calendaring special-focus current-events announcements
excerpt: The CalConnect XXVII meeting in Nottingham is now rescheduled again, from June 2020 to October 12-16, 2020.  All other arrangements (host, venue, conference hotel) remain unchanged.  The Board has reached this decision after reviewing the current status of the pandemic, as available from the WHO and CDC, and concluded that the chance of having a successful in-person conference in June is very slim.
---

== CalConnect XLVII Rescheduled to October 12-16, 2020

[[node-522]]
Posted April 12, 2020 

The CalConnect XXVII meeting in Nottingham is now rescheduled again, from June 2020 to October 12-16, 2020.&nbsp; All other arrangements (host, venue, conference hotel) remain unchanged.&nbsp; The Board has reached this decision after reviewing the current status of the pandemic, as available from the WHO and CDC, and concluded that the chance of having a successful in-person conference in June is very slim.

&nbsp;We recommend that those planning to attend the Nottingham meeting avoid non-changeable travel arrangements until we can confirm the meeting will be held in October. You can of course still register for the meeting, and can defer registration payment until the meeting.

Our apologies for the inconvenience and uncertainty.&nbsp; We hope the Nottingham meeting in October will proceed apace.



Categories:&nbsp;

link:/news/the-world-of-calendaring[The World of Calendaring]

link:/news/special-focus[Special Focus]

link:/news/current-events[Current Events]

link:/news/announcements[Announcements]

