---
layout: page
title: Registration is now open  for the CalConnect Virtual Conference October 12-15, 2020
date: 2020-09-17
type: news
categories: special-focus current-events announcements
excerpt: The CalConnect Virtual Conference web page  contains information about the timing, structure, and sessions offered for this virtual conference.  .
---

== Registration is now open  for the CalConnect Virtual Conference October 12-15, 2020

Posted September 17, 2020 

The https://www.calconnect.org/events/calconnect-virtual-conference-2020[CalConnect Virtual Conference web page] contains information about the timing, structure, and sessions offered for this virtual conference. .

The CalConnect Conference is planned for four days, Monday-Thursday, October 12-15, with the possibility of scheduling additional working sessions or testing on Friday October 16.

The conference will be held via Zoom and we expect will last approximately 3-3.5 hours each day. Monday through Wednesday will be scheduled from 1100 to 1400 Eastern Standard Time. Thursday will be scheduled for our Asia/Pacific members and will begin at 0100 Eastern Standard Time.

Please see the https://www.calconnect.org/events/calconnect-virtual-conference-2020[CalConnect Virtual Conference web page] for more information, including the planned schedule for the event.

*Fees and Registration Options*: The registration fee for the conference is $50 per person for members and non-members alike.&nbsp; Registration information is at https://www.calconnect.org/events/event-registration-payment and is linked from the event web page. Please note that all registrations must be paid in advance of the conference.&nbsp;

Event access information and credentials will be e-mailed to all registered participants late in the week prior to the conference. You *must be registered* to attend the event.


