---
layout: page
title: New CalConnect Membership Category; Small Organizational Member
date: 2020-11-29
type: news
categories: special-focus current-events press-releases announcements
excerpt: CalConnect has added a new membership category, “small organizational member”, effective immediately. This membership category is intended for very small organizations such as independent client developers, that have minimal staff and revenue.  The membership fee is $1,000 per year.
---

== New CalConnect Membership Category: Small Organizational Member

[[node-536]]
Posted November 29, 2020 

CalConnect has added a new membership category, small organizational member, effective immediately. This membership category is intended for very small organizations such as independent client developers, that have minimal staff and revenue.&nbsp; The membership fee is $1,000 per year.

Please see https://www.calconnect.org/membership-categories-and-fees[Membership Categories and Fees]&nbsp; and https://www.calconnect.org/membership/membership-application[Membership Application] for more information, or contact mailto:executive.director@calconnect.org[executive.director@calconnect.org] with any questions.&nbsp;

https://www.addthis.com/bookmark.php?v=300https://www.addthis.com/bookmark.php?v=300https://www.addthis.com/bookmark.php?v=300https://www.addthis.com/bookmark.php?v=300https://www.addthis.com/bookmark.php?v=300

Categories:&nbsp;

link:/news/special-focus[Special Focus]

link:/news/current-events[Current Events]

link:/taxonomy/term/17[Press Releases]

link:/news/announcements[Announcements]

