---
layout: page
title: CalConnect Nottingham Rescheduled to April 19-23, 2021
date: 2020-07-20
type: news
categories: the-world-of-calendaring current-events press-releases announcements
excerpt: The CalConnect Nottingham Conference has been rescheduled again, from October 2020 to April 19-23, 2021.  All other arrangements (host, venue, conference hotel) remain unchanged.  The Board has reached this decision after reviewing the current status of the pandemic, as available from the WHO and CDC, and concluded that the chance of having a successful in-person conference in 2020 is very slim.
---

== CalConnect Nottingham Rescheduled to April 19-23, 2021

Posted July 20, 2020 

The CalConnect Nottingham Conference has been rescheduled again, from October 2020 to April 19-23, 2021. All other arrangements (host, venue, conference hotel) remain unchanged. The Board has reached this decision after reviewing the current status of the pandemic, as available from the WHO and CDC, and concluded that the chance of having a successful in-person conference in 2020 is very slim.

We recommend that those planning to attend the Nottingham meeting avoid non-changeable travel arrangements until we can confirm the meeting will be held in April 2021. You can of course still register for the meeting, and can defer registration payment until the meeting.

Our apologies for the inconvenience and uncertainty. We hope the Nottingham meeting in April will be possible and hope to see you there.


link:{{'/taxonomy/term/17' | relative_url}}[Press Releases]

