---
layout: page
title: Registration is open for the October 2021 CalConnect Virtual Conference
date: 2021-09-02
type: news
categories: the-world-of-calendaring current-events announcements
excerpt: The CalConnect Virtual Conference Autumn 2021 web page  contains information about the timing, structure, and sessions offered for this virtual conference.  .
---

== Registration is open for the October 2021 CalConnect Virtual Conference

[[node-550]]
Posted September 2, 2021 

The https://www.calconnect.org/events/calconnect-virtual-conference-autumn-2021[CalConnect Virtual Conference Autumn 2021] web page&nbsp; contains information about the timing, structure, and sessions offered for this virtual conference.&nbsp; .

The CalConnect Conference is planned for four days, Monday-Thursday, October 18-21, with the possibility of scheduling additional working sessions or testing on Friday October 22.

The conference will be held via Zoom and we expect will last approximately 3-3.5 hours each day.&nbsp; Monday through Wednesday will be scheduled from 1030 to 1400 Eastern Standard Time.&nbsp; Thursday will be scheduled for our Asia/Pacific members and will begin at 0100 Eastern Standard Time.

Please see the https://www.calconnect.org/events/calconnect-virtual-conference-autumn-2021[CalConnect Virtual Conference Autumn 2021] web page for more information, including the planned schedule for the event.

Fees and Registration Options:&nbsp; The registration fee for the conference is $50 per person for members and non-members alike.&nbsp;&nbsp; Registration information is at https://www.calconnect.org/events/event-registration-payment and is linked from the event web page.&nbsp; Please note that all registrations must be paid in advance of the conference.

Event access information and credentials will be e-mailed to all registered participants late in the week prior to the conference.&nbsp; You must be registered to attend the event.



Categories:&nbsp;

link:/news/the-world-of-calendaring[The World of Calendaring]

link:/news/current-events[Current Events]

link:/news/announcements[Announcements]

