---
layout: page
title: Conferences Rescheduled; Nottingham now May 2022
date: 2021-07-07
type: news
categories: the-world-of-calendaring general-information current-events press-releases announcements
excerpt: The CalConnect Nottingham Conference has been rescheduled once more, to May 09-13, 2022, and another Virtual Conference scheduled for October 18-22, 2021.
---

== Conferences Rescheduled; Nottingham now May 2022

Posted July 7, 2021 

The CalConnect Nottingham Conference has been rescheduled once more, to May 09-13, 2022, and another Virtual Conference scheduled for October 18-22, 2021.

All other arrangements for the Nottingham conference(host, venue, conference hotel) remain unchanged. The Board has reached this decision after reviewing the current status of the pandemic, as available from the WHO and CDC, and concluded that the chance of having a successful in-person conference before next year was essentially zero.

Additionally, CalConnect will host another Virtual Conference the week of October 18-22, 2021, modeled after the previious virtual conference earlier in 2021, but including some new calendaring-related material.

Our apologies for the inconvenience and uncertainty. We hope the Nottingham meeting in May 2022 will be possible to hold, and hope to see you there. And meantime, we'll see you vrtually in October.


link:{{'/taxonomy/term/17' | relative_url}}[Press Releases]

