---
layout: page
title: April Conference Schedule and Highlighted Sessions
date: 2021-02-18
type: news
categories: special-focus current-events announcements
excerpt: |
  The preliminary schedule for our April 2021 Virtual Conference is now
  available.
---
:page-liquid:

== April Conference Schedule and Highlighted Sessions

The *preliminary schedule* for our April 2021 Virtual Conference is now available at link:{{'/events/calconnect-virtual-conference-2021#conference-schedule' | relative_url }}[link].

*Highlighted sessions:*

*Monday 12 April 1200-1300* *Implementing JSCalendar* +
Report on implementing JSCalendar in Bedework and Fastmail

*Tuesday 13 April 1100-1200:* *DMARC and iMIP Constraints and Incompatibilities* +
There are known issues with iMip and DMARC. For example, forwarding of invitations and sending on behalf of another user. We will outline the problems and possibly suggest solutions.

*Wednesday 1100-1200:* *Calendaring, Public Events and Higher Education* +
A discussion on the calendar issues facing higher ed institutions. These include resource management and event publication.

*PLEASE NOTE:* *We are very interested in suggestions and proposals for additional sessions from members and non-members alike.* Please send any ideas, suggestions or proposals to mailto:contact@calconnect.org?subject=Session%20proposal%20for%20April[contact@calconnect.org].

