---
layout: page
title: Registration is open for the October 2021 CalConnect Virtual Conference
date: 2021-09-02
type: news
categories: the-world-of-calendaring current-events announcements
excerpt: The CalConnect Virtual Conference Autumn 2021 web page contains information about the timing, structure, and sessions offered for this virtual conference.
---
:page-liquid:

== Registration is open for the October 2021 CalConnect Virtual Conference

Posted September 2, 2021

The link:{{'/events/calconnect-virtual-conference-autumn-2021' | relative_url }}[CalConnect Virtual Conference Autumn 2021] web page contains information about the timing, structure, and sessions offered for this virtual conference.

The CalConnect Conference is planned for four days, Monday-Thursday, October 18-21, with the possibility of scheduling additional working sessions or testing on Friday October 22.

The conference will be held via Zoom and we expect will last approximately 3-3.5 hours each day. Monday through Wednesday will be scheduled from 1030 to 1400 Eastern Standard Time. Thursday will be scheduled for our Asia/Pacific members and will begin at 0100 Eastern Standard Time.

Please see the link:{{'/events/calconnect-virtual-conference-autumn-2021' | relative_url }}[CalConnect Virtual Conference Autumn 2021] web page for more information, including the planned schedule for the event.

Fees and Registration Options: The registration fee for the conference is $50 per person for members and non-members alike. Registration information is at link:{{'/events/event-registration-payment' | relative_url }} and is linked from the event web page. Please note that all registrations must be paid in advance of the conference.

Event access information and credentials will be e-mailed to all registered participants late in the week prior to the conference. You must be registered to attend the event.


