---
layout: page
title: Conferences rescheduled again; Nottingham will be in October 2022
date: 2022-01-20
type: news
categories: the-world-of-calendaring special-focus general-information current-events
excerpt: The CalConnect Nottingham Conference has been rescheduled once more, to October 10-14, 2022, and Virtual Conferences planned for Spring 2022.
---

== Conferences rescheduled again; Nottingham will be in October 2022

Posted January 20, 2022 

The CalConnect Nottingham Conference has been rescheduled once more, to October 10-14, 2022, and Virtual Conferences planned for Spring 2022.

All other arrangements for the Nottingham conference (host, venue, conference hotel) remain unchanged. The Board has reached this decision after reviewing the current status of the pandemic, as available from the WHO and CDC, and concluded that the chance of having a successful in-person conference before the autumn was essentially zero.

Additionally, CalConnect will host another Virtual Conference or conferences in the Spring of 2022.

Our apologies for the inconvenience and uncertainty. We hope the Nottingham meeting in October will be possible to hold, and hope to see you there. And meanwhile, we'll see you vrtually this Spring.


