---
layout: page
title:  Who May Join CalConnect?
type: membership
---

== Who May Join CalConnect?

Membership in CaConnect is open to any organization or individual
interested in furthering the goals of the Consortium upon submission and
acceptance of a membership application, agreement to abide by the rules
of the Consortium, and payment of the appropriate membership fee.
CalConnect invites members from

* Producers and vendors of Calendaring and Scheduling applications,
products and services, and related areas
* Open source organizations interested in Calendaring and Scheduling
implementations
* Academic Institutions
* Customers interested in Calendaring and Scheduling and in supporting
the goals of the Consortium and influencing the direction of technology
evolution
* Standards-setting organizations
* Individuals interested in the Consortium
* Organizations interested in participation in standards development
within CalConnect and via our liaisons with other international
standards organizations such as ISO