---
layout: page
title: Intellectual Property Rights Policy
type: about
permalink: /about/policies/intellectual-property-rights-policy
---
= Intellectual Property Rights Policy

_As of Feb 2025_

== 1. Introduction

CalConnect provides direction and influence by identifying and stating
needs and requirements and by developing and publishing open standards
itself,  as well as progressing specifications into appropriate other
standards-setting organizations.  CalConnect also actively participates
in the work of other standards bodies via liaison agreements.   As a
proponent and developer of open standards, CalConnect has adopted a
patent policy and IPR practices that align with major international
standardization bodies including ISO, IEC and ITU.

== 2. IPR Policy and guidelines

https://standards.calconnect.org/csd/cc-10003.html[CC/DIR 10003]
provides the CalConnect patent policy, which mirrors closely the "Common
Patent Policy for ITU-T/ITU-R/ISO/IEC".

https://standards.calconnect.org/csd/cc-10005.html[CC/DIR 10005]
provides guidelines for implementation of the CalConnect patent policy,
and specific steps on the operation of filing IPR statements.  It is
fully aligned to the "Guidelines for Implementation of the Common Patent
Policy for ITU-T/ITU-R/ISO/IEC" jointly published by IEC, ISO and ITU.

https://standards.calconnect.org/csd/cc-10005.html[CC/DIR 10005] further
specifies the establishment of a "Patent Information Database” to allow
CalConnect members to file IPR statements on IPR positions, similar to
the processes performed at standardization organizations including at
ISO, IEC, ITU and IETF.

https://standards.calconnect.org/csd/cc-10006.html[CD/DIR 10006] is the
CalConnect Intellectual Property RIghts Policy.

This alignment provides assurance to organizations and partners who work
with CalConnect, knowing that IPR practices at CalConnect are
international best practices.

It is the policy of CalConnect that no confidential material is to be
discussed at or during CalConnect activities. All information provided
or discussed in CalConnect activities is presumed to be public
information and member participants are reminded that they should not
discuss or reveal any confidential information of their respective
companies. While work in progress within CalConnect is not publicly
available other than to CalConnect members, with minor exceptions
completed work products  are intended to be publicly and freely
available and will be posted on the CalConnect web site. See
https://standards.calconnect.org/csd/cc-10006.html[CD/DIR 10006] Section
4.1.

== 3. Contributions

The term "contribution" refers to material provided by a member of
CalConnect during any activity, and may also refer to to material
provided by others on a Consortium external discussion list.
Participants in CalConnect activities, whether in person or via
electronic means, must avoid contributions which contain confidential
material. Contributions which contain intellectual property of an
organization must be disclosed and are subject to the rules and guidance
as stated above.  No material which is subject to any terms of
confidentiality or restriction of dissemination on the part of its
contributor or the contributor's organization can be accepted for such
use. Individuals participating in the activities of CalConnect are
responsible for determining that material which they contribute is made
available by their organizations in accordance with this provision.  See
https://standards.calconnect.org/csd/cc-10006.html[CD/DIR 10006] Section
4.2.

== 4. Copyright Provisions

If any part of a contribution is or may be subject to copyright, the
contributor and his or her organization, and any other owners of any
proprietary rights in the contribution, grant an unlimited perpetual,
non-exclusive, royalty-free, world-wide right and license to  CalConnect
under any copyrights in the contribution. This license includes the
right to copy, publish and distribute the contribution in any way, and
to prepare derivative works that are based on or incorporate all or part
of the contribution, the license to such derivative works to be of the
same scope as the license of the original contribution.  See
https://standards.calconnect.org/csd/cc-10006.html[CD/DIR 10006] Section
5.3.
