---
layout: page
title: CalConnect Major Work Projects
type: about
---

== CalConnect Major Work Projects

What we are working on now – major projects underway in CalConnect
Technical Committees – become a member and help make these things
happen.


[[work-projects]]
=== Abstract Calendaring API

link:/7_things_api.shtml[*Abstract Calendaring API*] - We need a full
"CRUD" (Create/Read/Update/Delete) Abstract Application Programming
Interface and Calendaring Architecture for Calendaring and Scheduling.

An Abstract Calendaring API from which fully compliant interfaces can be
created will enable "Calendaring as a Platform" -- that is, any process
running on a system can use the API to perform calendar and scheduling
oeprations against any calendaring and scheduling implmentation running
on that system. link:/tc-api.shtml[TC API].

==== Autodiscovery

*Autodiscovery* - "One-stop setup for devices and new service providers
for calendaring, e-mail, etc. based on internet standard protocols"

Currently there is no simple, "one-stop" way to set up a collection of
internet standard services such as e-mail, calendaring, and so forth.
This is an issue when someone starts with a new organization or changes
service proficers, and is even more difficult when one acquires a new
smartphone. We are working on a new standard protocol to specify how to
automatically discover and set up internet standards-based services such
as e-mail, calendaring, address book, etc. which can be implemented in a
single, easy to use user interface. link:/tc-autodiscovery.shtml[TC
AUTODISCOVERY].

==== CalDAV Alarms

*CalDAV Alarms* - "Extend alarm support to allow for cross-device
dismissal, proximity triggers based on location, default alarms in
CalDAV"

Sharing calendars and tasks across multiple devices is great - having
the alarms go off on all of them isn't. This extension to CalDAV (the
standard calendar service protocol) will allow for effective user
management of alarms, including choosing which device(s) should enable
each alarm, and the form of the alarm. link:/tc-caldav.shtml[TC CALDAV].

==== CalDAV Attachments

*CalDAV Attachments* - "Extend the calendaring server to manage
attachments"

This CalDAV extension will provide an interoperable and efficient
mechanism to allow clients to store and manage attachments associated
with a meeting (e.g. copy of a presentation, agenda,...) on a CalDAV
server. Beyond the basic storage aspect, the server also becomes
responsible for ensuring that only attendees of a meeting have access to
those attachments. link:/tc-caldav.shtml[TC CALDAV].

==== Calendars and Contacts Sharing

*Calendars and Contacts Sharing* - "Sharing calendars and contacts
between users, on the same system or across systems"

link:/tc-sharing.shtml[TC SHARING] is working on sharing calendars anc
contacts between users on a CalDAV and/or CardDAV system by
rationalizing and extending current informal specifications.
link:/tc-fsc.shtml[TC FSC] (Federated Shared Calendars) is working on
sharing calendars and hopefully contacts across calendaring system, e.g
being able to share between multiple systems such as iCloud, Google
Calendar, Yahoo!, AOL, and so forth.

==== CalWS-REST and CalWS-SOAP

*CalWS-REST and CalWS-SOAP* - "We need to (finally) provide platform and
system-independent calendaring and scheduling operations APIs for web
services - it's long past time"

Calendaring (and scheduling) should be available as a service on any
platform with a calendaring system installed, much like middleware. To
make this work and expose the calendaring system to other applications,
widgets, and so forth, we need a platform-independent and
system-independent API for calendaring operations. CalWS-REST and
CalS-SOAP provide both RESTful and SOAPy web service implementations of
this API. The work is being done in partnership with OASIS; see OASIS
WS-Calendar below.

==== Consensus Scheduling (VPOLL)

link:/7_things_consensus_scheduling.shtml[*Consensus Scheduling (VPOLL)*]

"TimeTrade, Doodle, WhenisGood do it, it should be interoperable - scheduling
driven by the attendees who get to vote on the best times and locations for
group events"

Consensus scheduling involves using a poll-based or vote-based mechanism
to determine the date, time, location of an event or a task. This has
been implemented by several vendors in their own systems but should be
available and interoperable within mainstream scheduling. VPOLL is an
additional iCalendar and iTIP component designed to allow the
implementation of consensus scheduling with any system and client.
link:/tc-freebusy.shtml[TC FREEBUSY].

==== Developer's Guides

*Developer's Guides* - Create a "cookbook" guide and other supporting
materials for iCalendar and potentially other APIs such as CalDAV.

The lack of useful developer's guides and other documentation about
iCalendar, CalDAV, and other specifications is a problem for all current
and would-be developers in calendaring and scheduling.
link:/tc-devguide.shtml[TC DEVGUIDE] has been formed to address this
lack by creating a "cookbook" guide and other supporting materials for
iCalendar and potentially other APIs such as CalDAV.

==== Event Publishing Extensions

*Event Publishing Extensions* - "Calendaring standards need to support
the rich environment of Web 2.0 (and beyond) for the publication of
public events - rich text, participants and image support"

Events for publication require more and richer information than
conventional meeting events. CalConnect is working on defining some new
properties:

structured locations - perhaps as vcards

participants - for example, the team, audience, principal performer,
contacts

rich and locale-specific descriptions - allows html and multi-language
support

images

link:/tc-eventpub.shtml[TC EVENTPUB].



==== iSCHEDULE

*iSCHEDULE* - "We need server to server scheduling between dissimilar
systems - we have had client to server scheduling for a long time"

Scheduling a meeting between co-workers on a single calendaring system
has been available for a long time, but trying to schedule with people
on different calendar servers has only be available by hooking it onto
emails. iSchedule provides a system-independent server-to-server
mechanism to allow inter-system scheduling and ultimately "ad hoc"
scheduling - the ability to schedule a meeting or appointment with
anybody with a calendar and a calendar server, regardless of what system
they are on. link:/tc-ischedule.shtml[TC ISCHEDULE].

==== Non-Gregorian Calendars

*Non-Gregorian Calendars* - "Establish a way for recurrences to work
with non-Gregorian calendar systems, in particular lunar/solar
calendars"

We have established the CALSCALE Ad Hoc committee to develop a draft
proposal for supporting recurrences for non-gregorian calendars via the
CALSCALE parameter in iCalendar and an RSCALE extension to RRULE. The
goal is to allow clients supporting non-gregorian calendars to create
recurring events without having to implement non-standard mechanisms. At
this point the draft has been submitted to the IETF and the discussion
is expected to continue on IETF mailing lists; we are not sure what
further work will be done within CalConnect.

==== OASIS WS-Calendar

*OASIS WS-Calendar* - "Working with OASIS to develop their new
WS-Calendar standard (scheduling for the Smart Grid), based on xCal,
CalWS-REST and CalWS-SOAP"

We are working with OASIS (the Organization for the Advancement of
Structured Information Systems) to develop their WS-Calendar standard.
It was original intended for the exchange of power information for the
smart grid, and is based on xCal (iCalendar in XML) and CalWS (web
services API for calendaring) protocols developed by CalConnect. OASIS
and CalConnect maintain reciprocal memberships and liaisons between
their WS-Calendar technical committee and our technical committees.

==== PUSH for CalDAV

link:/7_things_push.shtml[*PUSH for CalDAV (and CardDAV)*] - "Extend
CalDAV and CardDAV with standardized support for PUSH notifications"

At present CalDAV and CardDAV clients have to poll the server at regular
intervals to check for changes. To provide a close to "real time" user
experience and present updates and notifications almost immediately to
the user, a client has to poll at a high frequencies, possibly at the
expense of higher consumption of resources like bandwidth and traffic,
processing time and battery power. We will define methods to
advertise/discover PUSH protocols supported by a server. In addition it
will specify a generic PUSH protocol based on existing WebDAV
technologies that can be used when no other PUSH method is available. To
help implementers we will provide guidelines to PUSH support on servers
and clients.

==== Tasks (VTODOs)

link:/7_things_tasks.shtml[*Tasks (VTODOs)*] - "Extend the functionality
of VTODOs to support needs such as project management, smart power grids
and business task scheduling"

The VTODO component of iCalendar must be extended to offer functionality
for new use cases such as the smart grid, project management, and
business task scheduling, in a way that allow a calendaring system to
manage the data and calendaring clients to display and change it.
link:/tc-tasks.shtml[TC TASKS] is working on extending iCalendar in
areas such as project managment, WS Human Task, and smart grid energy
management.

==== Timezone service and registry

*Timezone service and registry* - "Full timezone support via dynamic
server calls rather than embedding timezone information in events - no
more having event times wrong when timezones change and your software
isn't updated"

Traditionally calendar entries coded in iCalendar have had to include
timezone information to allow interpretation of the date and time of an
event, and can be incorrect if the timezones have changed since the
information was put in the event. Having a separate, online timezone
service which can be queried at any time will allow timezone information
to be included by reference in events, rather than embedded in them, and
ensure correct interpretation of dates and times even if the information
changes. link:/tc-timezone.shtml[TC TIMEZONE].

==== VAVAILABILITY

*VAVAILABILITY* - "New iCalendar component to describe availability, to
'condition' freebusy lookup and scheduling (e.g. you may be 'free' at 3
a.m. but you aren't available for a meeting)"

VAVAILABILITY is a new component for iCalendar which allows an
indivdiual to specify when they are available to be scheduled for
meetings (As opposed to "busy" when they already have a meeting
scheduled, or "free" when nothing is scheduled). VAVAILABILITY will also
allow the implementation of "office hours" applications, in particular
for academic institutions, and has significant use also in the smart
grid work being undertaken by OASIS. link:/tc-freebusy.shtml[TC
FREEBUSY].

==== vCard Resources

*vCard Resources* - "Define the vCard representation of calendaring
resources to ease the discovery and scheduling of resources between any
calendar client and server"

In keeping with the goal of TC RESOURCE to develop recommendations for
seamless interoperable resource scheduling, we have been working on
defining how such resources should be represented. RFC 6350 defines the
vCard format which allows the electronic capture and exchange of
information on users, devices, and more. link:/tc-resource.shtml[TC
RESOURCE] is working on an extension of the vCard RFC to include all
required information for representing calendaring resources.