---
layout: page
title: Technical Committees and Provisional Committees
type: about
---
:page-liquid:
= Technical committees and provisional committees

_Last Updated October 2020_

== General

Technical Committees are the technical working groups of CalConnect. A Technical
Committee is established with a specific charter (scope of work), time frame,
deliverables and expected schedule, and will disband when its scope of work is
completed.

Provisional Committees may be established at a CalConnect Conference to explore
a possible new work area of work and recommend whether CalConnect should move
forward in that area, generally by forming a new Technical Committee.
Provisional Committees are usually very short-lived, reporting out at the next
Conference.

The work of Technical Committees and Provisional Committees is guided and
coordinated by the Technical Coordination Committee (TCC).

Technical Committees generally produce CalConnect Work Products: Reports,
Recommendations, specifications, code artifacts, etc. Technical Committees also
produce draft specifications which may be published by CalConnect as a
CalConnect Standard, and/or submitted to an external SDO for progression within
that organization. Finally Technical Committees may also collaborate externally
towards the development of material which will not become a CalConnect Work
Product but may be part of some other joint effort. See
link:{{'/resources' | relative_url}}[CalConnect Resources] for more information.

Representatives of CalConnect members may participate upon any Technical
Committee by contacting the Chair of the TC. Members may propose new Technical
Committees to address areas of work not currently under consideration, and may
offer a Chair for a new TC (or PC).

For Closed Technical Committees please see link:{{'/about/technical-committees/closed-tcs' | relative_url }}[Closed Technical Committees].


== Technical Coordination Committee (TCC)

Details: link:{{'/about/technical-committees/tcc/' | relative_url}}[Technical Coordination Committee (TCC)]

The TCC consists of the Chairs of the active Technical Committees and
Provisional Committees, and functions as an ongoing status and coordination
group for the Technical Committees under the guidance of the Board of Directors
or its representative. The Chair of the TCC is appointed by the Board upon
recommendation by the Chairs of the Technical Committees and after a periodic
call to the membership for volunteers. The TCC meets by conference call and
electronically on a regular basis as determined by the committee, generally
weekly, to ensure that TC activities are monitored and guided as necessary. The
TCC is also responsible for final approval for publication of Technical
Committee documents which have passed Last Call status, and with planning for
upcoming CalConnect events.

== Technical committees

=== TC-API: Abstract API for calendaring and scheduling

Details: link:{{'/about/technical-committees/tc-api/' | relative_url}}[TC-API Charter]

Develop an Abstract API for Calendaring and Scheduling.

=== TC-AUTODISCOVERY: Service autodiscovery

Details: link:{{'/about/technical-committees/tc-autodiscovery/' | relative_url}}[TC-AUTODISCOVERY Charter]

Autodiscovery of services based on internet standard protocols.

=== TC-CALENDAR: Calendar improvements and extensions

Details: link:{{'/about/technical-committees/tc-calendar/' | relative_url}}[TC-CALENDAR Charter]

Improvements and extensions to iCalendar, CalDAV, and iTIP transports, including but not limited to: iCalendar diff/patch, more compact recurrences, extensions to tasks, consensus scheduling, best current practices for iMIP, and iTIP over HTTP (iSchedule).

=== TC-CALSPAM: Calendar spam prevention

Details: link:{{'/about/technical-committees/tc-calspam/' | relative_url}}[TC-CALSPAM Charter]

The TC aims to understand the current and potential usage of calendar systems as a vector for delivering undesired information; devise measures and best practices for developers and operators of those systems to ensure legitimate usage.

=== TC-CLIENT: Calendar client perspective

Details: link:{{'/about/technical-committees/tc-client/' | relative_url}}[TC-CLIENT Charter]

TC-CLIENT strives to put an emphasis on the calendar client perspective and to bring together developers of calendar clients and those interested in client-related topics.

=== TC-DATETIME: Date and time standards

Details: link:{{'/about/technical-committees/tc-datetime/' | relative_url}}[TC-DATETIME Charter]

TC-DATETIME is the home for all date and time related work undertaken in CalConnect and between CalConnect and external liaison organizations.

=== TC-DEVGUIDE: Developer guides

Details: link:{{'/about/technical-committees/tc-devguide/' | relative_url}}[TC-DEVGUIDE Charter]

Develop "cookbook" and supporting materials on how to use iCalendar and potentially other APIs such as CalDAV.

=== TC-LOCALIZATION: Localization standards

Details: link:{{'/about/technical-committees/tc-localization/' | relative_url}}[TC-LOCALIZATION Charter]

Enable standardization of localization technologies and approaches, and topics relevant to the usage of localization.

=== TC-PUBLISH: Document publication

Details: link:{{'/about/technical-committees/tc-publish/' | relative_url}}[TC-PUBLISH Charter]

Develop and maintain CalConnect document requirements and publication processes for CalConnect Standards and other public documents.

=== TC-PUSH: Push notifications

Details: link:{{'/about/technical-committees/tc-push/' | relative_url}}[TC-PUSH Charter]

Define a generic framework for push notifications within CalDAV (and CardDAV).

=== TC-SHARING: Resource sharing

Details: link:{{'/about/technical-committees/tc-sharing/' | relative_url}}[TC-SHARING Charter]

Extend the existing caldav-sharing and caldav-notifications specifications to support address books and other resource types.

// === TC-STREAMING: Calendar data streaming

// Details: link:{{'/about/technical-committees/tc-streaming/' | relative_url}}[TC-STREAMING Charter]

// Define and document a streaming protocol for calendar data.

=== TC-TESTER: Testing framework

Details: link:{{'/about/technical-committees/tc-tester/' | relative_url}}[TC-TESTER Charter]

Generalize and extend capabilities of the CalDAV/CardDAV Tester.


=== TC-UNITS: Contact information standards

Details: link:{{'/about/technical-committees/tc-units/' | relative_url}}[TC-UNITS Charter]

Establish international standards for representation and encoding of units,
quantities, and dimensions, and the mechanisms for encoding and interpretation
of formulas that utilize units.

=== TC-VCARD: Contact information standards

Details: link:{{'/about/technical-committees/tc-vcard/' | relative_url}}[TC-VCARD Charter]

Extend VCARD standards to support world-wide address formats and new capabilities.


== Ad-hoc committees

=== iCal4J development

Develop a CalConnect version of iCal4J usable by all members and drive back into
the mainline iCal4J.
