---
layout: page
title: CalConnect Calendars
type: events
---

== CalConnect Calendars

_As of 06 June 2021_

NOTE: If you subscribed to any of these calendar feeds prior to June 2021, you
must unsubscribe and resubscribe using the links below.  A change was made to
the naming convention for icloud calendar subscriptions at the end of May.

CalConnect maintains two major calendars, a master calendar for ongoing
conference calls and related activities, and a conference calendar for each
CalConnect Event's schedule. In addition, sub-calendars with the events for an
individual Technical Committee or other CalConnect committee may be individually
subscribed to or downloaded, and a subcalendar for the set of infrequently
scheduled calls is also available.

The links below for each calendar will allow you to subscribe to the public
shared calendars.

NOTE: Although the calendars are publicly available, you must be a
representative of a CalConnect member to attend CalConnect conference calls.

NOTE: CalConnect's use of a shared calendar service does not represent an
endorsement or recommendation of that calendaring service or vendor, or any
other calendaring service or vendor.


=== Ongoing CalConnect Conference Calls and Activities

"CalConnect_Calendar" is the combined master calendar containing events
(generally recurring) for all scheduled CalConnect committee calls and related
activities until the next CalConnect Conference. It is usually updated each
Monday following the TCC Technical Coordinating Committee call, to reflect any
changes to the schedule as identified at the TCC call. The individual committee
calendars contain only those events relevant to that committee.

[cols=",",]
|===
|Calendar |*subscribe* to this calendar

|*CalConnect_Calendar*
|
link:webcal://p48-caldav.icloud.com/published/2/PhsnNIf3otjjRswv8DhQHhIXAEgPBmBzxL1YHIYfT5jmkaJEzA-snuNosN8PAgE6VXtdyZfYKxkjSHTmPfp5fTRwC-5rF5GdJ3f6DsPAcq0[click here]

|*Board_of_Directors*
|
link:webcal://p48-caldav.icloud.com/published/2/jNv2Cs2oEWMhV2wzKVcXZYi10qsfWqo0liSMn3bNmZFbcVAirmZKwAJwh9wi-FZjHAOKlei83O5XhzZ2alVQIOrw5FdY9sS-QCuB4dTjEnI[click here]

|*Event_Planning*
|
link:webcal://p48-caldav.icloud.com/published/2/nNGX2lGFZ5oBDereT3K-O5P_aKyLimt_5SIxjG2D5l4b2PSfDbQN9CqPNvTZ1XUxvEl-sV1dFC5NN6qzL95Hk-kxSbllOqKkHUpeNd1NTUc[click here]

|*MarCom*
|
link:webcal://p48-caldav.icloud.com/published/2/AAAAAAAAAAAAAAAAAAAAAAA8d83fZoFlTR54yaPPPrCJhpSNa7s1xy3pYQ_oKTYSTiwDf0hrXrf4y6VSVkSXd6M-Ui8ypDRdUncbUw1-HIE[click here]

|*TCC*
|
link:webcal://p48-caldav.icloud.com/published/2/MjA5OTc4NTc4MjA5OTc4NYPAre1eU33EoiR3Bg4yHV4icYsjNN3Uzsw9x9WG0lzQ5Muq52Nshz7YO1tZsS7DYvkEUxqMImgzP44a02GGyaY[click here]

|*TC-CALENDAR*
|
link:webcal://p48-caldav.icloud.com/published/2/dSUpewv79UfhExQrrKuXgF_TQz9YrzGvJRLNs7ql1pBNUwui2I8EH7oaiW1fTnbNxdLn0JSmlg9XAwhEfRNXdytE7_PNVZimdWXDQsf_jj4[click here]

|*TC-CALSPAM*
|
link:webcal://p48-caldav.icloud.com/published/2/AAAAAAAAAAAAAAAAAAAAAPt32jQikub55iiytC9_eGB8eNna1vYfaRiLGz50-zgA-l6dS9wMyA2E1mfd5W286r8_Qeg3umXsv4__XWaCGMk[click here]

|*TC-CLIENT*
|
link:webcal://p48-caldav.icloud.com/published/2/MjA5OTc4NTc4MjA5OTc4NYPAre1eU33EoiR3Bg4yHV5yhG6Hkfxua7pm3N_1lmx9YoQy-KYcZTsAtzElbIe_jGoIAqzzAEaXS8q9B-qqGVw[click here]

|*TC-DEVGUIDE*
|
link:webcal://p48-caldav.icloud.com/published/2/DaPvIsVSxVpyNRkNmLNmOSwpBf8LqiJNxMHO-fQz58VJPf7VLygmm6yOtrcZP3rKIDKabp2hhlLPd4fNlq3gaGET8TPZdA1Marjw1HxLcN8[click here]

|*TC-SHARING*
|
link:webcal://p48-caldav.icloud.com/published/2/ZCAt8RggQZqis1KHhvt6wRNgzKURmhkinMfYop3cYiCSqEezjQKU8J3ZvQ0oeEMNnMSpB99iUr1RoCMqtJE2UQFEsrGSKoKpxbyngIIJj9s[click here]

|*TC-STREAMING*
|
link:webcal://p48-caldav.icloud.com/published/2/njl567QsPg-2ZtX8D79hXwIlsln3ye21rDlki3IYOAjEsU2tABEX61URHOG9u9xwjZIK09DGADOpsy6BCgPlrOjS05Q3aEgfbT40g7m02s4[click here]

|===



==== CalConnect Conference Calendar

"CalConnect_Conference.ics" contains the schedule for the upcoming
CalConnect Event, which is comprised of both the Test Event/Developers
Forum and the Conference. _This file may have no events defined
following a CalConnect Conference and before the next Conference's
schedule is defined._

To subscribe to this calendar:

* link:webcal://p48-caldav.icloud.com/published/2/lYLdmehfxPPXFJb6UG45eNn1BtQ_JuuKwVffIvBx6CoC3tu_6W3vy2rY-ntnnPP3CVNSbw2-_vcAuwlN7O51PZ3494ByL9Jod25b3LJg_C8[click here].


NOTE: CalConnect's use of a shared calendar service does not represent an
endorsement or recommendation of that calendaring service or vendor, or
any other calendaring service or vendor.