---
layout: page
title: General Information on Conference Fees and Registration
type: events
---

== General Information on Conference Fees and Registration

_Current as of February 2019_

The registration fee covers morning coffee, lunch and breaks for the
four days of the Conference, plus the reception the first night and the
group dinner the evening before the last day (i.e. Wednesday or
Thursday)..  Rolls and pastries or fruit may also be offered with
morning coffee and tea.  +
 +
A tiered registration fee consisting of an early fee and a latecomer fee
is established. The purpose of the tiered fee is to encourage early
registration for the conference so CalConnect and the host can determine
counts and costs. The current Conference Registration Fee is *$950 for
early registration and $1050 for late registration. * A One Day
Registration is also offered; the current fee is $400 for early
registration and $475 for latecomers.  ("Early" means prior to two weeks
before the event.) +
 +
Registration will be opened for each Conference as early as possible,
and no less than six weeks prior to the event. +