---
layout: page
title: CalConnect Conferences
type: events
---

== CalConnect Conferences

_Current as of August 2019_

CalConnect Conferences (originally called "Roundtables") are largely
member events. Members may send as many representatives as they wish,
although there may be a maximum number of attendees established by the
venue. Registration for the Conference is first-come, first-served.

Although attendance at CalConnect Conferences is generally limited to
CalConnect member representatives, a prospective member may send one or
more
link:/events/events-activities/observers[Observers]
to a single Conference to determine whether or not it wishes to join.
Observers pay the same registration fee as regular participants and may
participate in all Conference activities, but may not vote.

Additionally, organizations with which CalConnect has a liaison
relationship may send representatives to CalConnect Conferences.
Liaison representatives pay the same registration fee as regular
participants and may participate in all CalConnect activities, but may
not vote.

CalConnect holds two or three Conferences per year at regular
intervals.  The exact dates for each is agreed with the host when a
hosting offer is accepted, and prior to announcement of the dates and
venue..  CalConnect Conferences are currently four days, and may last
from Monday throught Thursday, or from Tuesday through Friday, also
agreed with the host before the Conference is announced.

The session schedule for the week and topical agendas for the Conference
sessions are posted on that event's logistics page.  Each day begins
with morning coffee at 0830-0900, followed by sessions in the morning,
lunch at 1230-1330, and sessions in the afternoon, ending at 1730.
Morning and afternoon breaks with refreshments are from 1030-1100 and
1530-1600.

An optional introductory Q&A for new attendees is usually held the first
morning. Opportunities for BOFs and informal chats are built into the
schedule.  Our current practice is to reserve the afternoon of the last
day (Thursday or Friday) for working sessions such as interoperability
testing and joint work on projects.

CalConnect may also schedule optional Tutorial sessions on calendaring
and schedule (and related) standards and specifications on Monday
morning if there is interest in them.

CalConnect provides morning coffee, lunch and breaks throughout the
Conference. There is also a Welcome Reception the first evening,
generally provided by the host, and a group dinner the evening prior to
the last day, provided by CalConnect.

Registration in advance is required for all individuals participating in
CalConnect Conferences, although if desired, payment may be done at the
Conference via credit card.